
// ── Configuration ──
// All values are injected at deploy time from `js/config.js` (generated by the
// GitHub Actions workflow from repository secrets). For local development copy
// `js/config.example.js` to `js/config.js` and fill in the values.
const _CFG = (window.DF_CONFIG || {});
const EMAIL_TO = _CFG.EMAIL_TO || 'adam@divokefarmy.cz';
const VAT = 0.12;

const _SUPA_URL = _CFG.SUPABASE_URL || '';
const _SUPA_KEY = _CFG.SUPABASE_ANON_KEY || '';
// If config is missing (local dev without backend, or CI failed to inject),
// fall back to a stub client so the page still renders the customer form.
// All network-dependent features (auth, orders, admin) become no-ops.
function _makeStubDb(){
  var noBackend = { data: null, error: { message: 'No backend configured.' } };
  function chain(){
    var q = {};
    ['select','insert','update','upsert','delete','eq','order','limit','single']
      .forEach(function(m){ q[m] = function(){ return q; }; });
    q.then = function(cb){ cb(noBackend); return { catch: function(){} }; };
    return q;
  }
  return {
    from: function(){ return chain(); },
    auth: {
      getUser: function(){ return Promise.resolve({ data: { user: null }, error: null }); },
      onAuthStateChange: function(){ return { data: { subscription: { unsubscribe: function(){} } } }; },
      signInWithPassword: function(){ return Promise.resolve(noBackend); },
      signUp: function(){ return Promise.resolve(noBackend); },
      signOut: function(){ return Promise.resolve({ error: null }); }
    }
  };
}
const _db = (_SUPA_URL && _SUPA_KEY)
  ? window.supabase.createClient(_SUPA_URL, _SUPA_KEY)
  : (console.warn('[df] No Supabase config — running in offline stub mode.'), _makeStubDb());

const EJS_KEY      = _CFG.EMAILJS_PUBLIC_KEY || '';
const EJS_SERVICE  = _CFG.EMAILJS_SERVICE_ID || '';
const EJS_TEMPLATE = _CFG.EMAILJS_TEMPLATE_ID || '';
if (EJS_KEY) emailjs.init({ publicKey: EJS_KEY });
const P = [
  {"cat":"Paštiky a pomazánky","name":"Foie gras paštika","baleni":"120 g","sklad":"lednice","trv":"4 měsíce","voc":92,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Foie gras s brusinkami","baleni":"120 g","sklad":"lednice","trv":"4 měsíce","voc":103,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Foie gras se zeleným pepřem","baleni":"120 g","sklad":"lednice","trv":"4 měsíce","voc":103,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Hrubá vepřová paštika","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Husí paštika","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":75,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Jemná vepřová paštika","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Kachní játrová paštika","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":75,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Polohrubá z divočáka","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":69,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Slaninový džem","baleni":"120 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Pikantní topinková směs","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":51,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Paštiky a pomazánky","name":"Zvěřinová paštika","baleni":"170 g","sklad":"lednice","trv":"4 měsíce","voc":69,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Vývary","name":"Hovězí vývar","baleni":"165 ml","sklad":"lednice","trv":"4 měsíce","voc":30,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Vývary","name":"Vepřový vývar","baleni":"165 ml","sklad":"lednice","trv":"4 měsíce","voc":30,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Vývary","name":"Drůbeží vývar","baleni":"165 ml","sklad":"lednice","trv":"4 měsíce","voc":30,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Zabijačkový guláš","baleni":"545 ml","sklad":"do 25°C","trv":"4 měsíce","voc":81,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Zabijačková polévka prdelačka","baleni":"545 ml","sklad":"do 25°C","trv":"4 měsíce","voc":57,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Zabijačková polévka ovarová","baleni":"545 ml","sklad":"do 25°C","trv":"4 měsíce","voc":57,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Vranovská vepřovka","baleni":"","sklad":"","trv":"4 měsíce","voc":91,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Pečený bok na medu a cibulce","baleni":"400 g","sklad":"","trv":"4 měsíce","voc":81,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Vepřové koleno ve vlastní šťávě","baleni":"280 g","sklad":"","trv":"4 měsíce","voc":81,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Pečené koleno v bylinkách","baleni":"280 g","sklad":"","trv":"4 měsíce","voc":81,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Dršťková polévka","baleni":"545 ml","sklad":"do 25°C","trv":"4 měsíce","voc":81,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Konzervy","name":"Husí játra v sádle","baleni":"","sklad":"","trv":"4 měsíce","voc":92,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Utopenci a nakládané","name":"Utopený švec","baleni":"130 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Utopenci a nakládané","name":"Pikantní utopenec v pivu","baleni":"130 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Utopenci a nakládané","name":"Utopenec klasik","baleni":"130 g","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Utopenci a nakládané","name":"Zavařené křepelčí vejce","baleni":"365 ml","sklad":"lednice","trv":"4 měsíce","voc":87,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Klobásy a salámy","name":"Klobása z divočáka – zelený pepř","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":50,"ok":false,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"Klobása z Gruntu – 1 kus","baleni":"100 g","sklad":"do 18°C","trv":"4 měsíce","voc":31,"ok":true,"vahy":true,"voc_kg":307.25},
  {"cat":"Klobásy a salámy","name":"Klobása z Gruntu – pár","baleni":"200 g","sklad":"do 18°C","trv":"4 měsíce","voc":62,"ok":true,"vahy":true,"voc_kg":307.25},
  {"cat":"Klobásy a salámy","name":"Maďarka","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":50,"ok":false,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"Klobása Pikoška – 1 kus","baleni":"100 g","sklad":"do 18°C","trv":"4 měsíce","voc":31,"ok":true,"vahy":true,"voc_kg":307.25},
  {"cat":"Klobásy a salámy","name":"Klobása Pikoška – pár","baleni":"200 g","sklad":"do 18°C","trv":"4 měsíce","voc":62,"ok":true,"vahy":true,"voc_kg":307.25},
  {"cat":"Klobásy a salámy","name":"Podkova s goudou","baleni":"130 g","sklad":"do 18°C","trv":"4 měsíce","voc":55,"ok":true,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"S jamajským rumem a brusinkami","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":50,"ok":true,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"S vlašskými ořechy","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":50,"ok":true,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"Španělka","baleni":"130 g","sklad":"do 18°C","trv":"4 měsíce","voc":55,"ok":true,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"Jelení huhuchilli","baleni":"115 g","sklad":"do 18°C","trv":"4 měsíce","voc":68,"ok":true,"vahy":true,"voc_kg":568.12},
  {"cat":"Klobásy a salámy","name":"Hovězí japaleno cheddar","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":68,"ok":false,"vahy":true,"voc_kg":568.12},
  {"cat":"Klobásy a salámy","name":"Skopová sušená klobása","baleni":"120 g","sklad":"do 18°C","trv":"4 měsíce","voc":50,"ok":false,"vahy":true,"voc_kg":423.19},
  {"cat":"Klobásy a salámy","name":"Kabanosky hovězí","baleni":"","sklad":"do 18°C","trv":"4 měsíce","voc":87,"ok":false,"vahy":false,"voc_kg":0},
  {"cat":"Párky a uzeniny","name":"Farmářská klobása","baleni":"270–300 g","sklad":"lednice","trv":"21 dní","voc":66,"ok":false,"vahy":true,"voc_kg":220.29},
  {"cat":"Párky a uzeniny","name":"Vepřový párek","baleni":"370–400 g","sklad":"lednice","trv":"21 dní","voc":100,"ok":true,"vahy":true,"voc_kg":178.57},
  {"cat":"Párky a uzeniny","name":"Klobása s medvědím česnekem","baleni":"","sklad":"lednice","trv":"21 dní","voc":0,"ok":false,"vahy":true,"voc_kg":220.29},
  {"cat":"Párky a uzeniny","name":"Klobása s nivou","baleni":"","sklad":"lednice","trv":"21 dní","voc":0,"ok":false,"vahy":true,"voc_kg":220.29},
  {"cat":"Párky a uzeniny","name":"Špekáček 2 kusy","baleni":"230–250 g","sklad":"lednice","trv":"21 dní","voc":38,"ok":true,"vahy":true,"voc_kg":150},
  {"cat":"Párky a uzeniny","name":"Špekáček 4 kusy","baleni":"","sklad":"lednice","trv":"21 dní","voc":76,"ok":true,"vahy":true,"voc_kg":150},
  {"cat":"Ostatní","name":"Medová šunka","baleni":"100 g","sklad":"lednice","trv":"7 dní","voc":23,"ok":true,"vahy":true,"voc_kg":231.30},
  {"cat":"Ostatní","name":"Sádlo malé","baleni":"600 ml","sklad":"lednice","trv":"4 měsíce","voc":63,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Ostatní","name":"Sekaná česnek","baleni":"500 g","sklad":"lednice","trv":"14 dní","voc":91,"ok":true,"vahy":true,"voc_kg":184.93},
  {"cat":"Ostatní","name":"Škvarková pomazánka","baleni":"200 g","sklad":"lednice","trv":"4 měsíce","voc":34,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Ostatní","name":"Vepřové škvarky v kyblíku","baleni":"200 g","sklad":"lednice","trv":"14 dní","voc":0,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Ostatní","name":"Tlačenka","baleni":"400–500 g","sklad":"lednice","trv":"10 dní","voc":75,"ok":true,"vahy":true,"voc_kg":150},
  {"cat":"Ostatní","name":"Kachní chipsy","baleni":"40 g","sklad":"do 25°C","trv":"4 měsíce","voc":57,"ok":true,"vahy":false,"voc_kg":0},
  {"cat":"Špeky","name":"Špek farmářský","baleni":"200 g","sklad":"lednice","trv":"3 měsíce","voc":40,"ok":true,"vahy":true,"voc_kg":200},
  {"cat":"Špeky","name":"Paprikový špek","baleni":"200 g","sklad":"lednice","trv":"3 měsíce","voc":40,"ok":true,"vahy":true,"voc_kg":200},
  {"cat":"Špeky","name":"Zauzený špek","baleni":"200 g","sklad":"lednice","trv":"3 měsíce","voc":43,"ok":true,"vahy":true,"voc_kg":215}
];
// ── state ──
let avail = {};
P.forEach(function(p,i){ avail[i] = p.ok; });
let prodOverrides = {};
let archived = {};
let deleted = {};
let customProds = [];
let stockQty = {};

function _applyState(d){
  if(d.avail) Object.assign(avail, d.avail);
  if(d.overrides && Object.keys(d.overrides).length){
    prodOverrides = d.overrides;
    Object.keys(prodOverrides).forEach(function(i){ if(P[i]) Object.assign(P[i], prodOverrides[i]); });
  }
  if(d.archived) archived = d.archived;
  if(d.deleted) deleted = d.deleted;
  if(d.custom_prods && d.custom_prods.length){
    customProds = d.custom_prods;
    customProds.forEach(function(p){ P.push(Object.assign({_custom:true},p)); });
  }
  Object.keys(prodOverrides).forEach(function(i){ if(prodOverrides[i] && prodOverrides[i].stock>0) stockQty[i]=prodOverrides[i].stock; });
}

function fmt(n){ return n.toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kč'; }
function changeQty(i,d){ var el=document.getElementById('q'+i); if(!el) return; var sq=stockQty[i]||0; var nv=Math.max(0,(parseInt(el.value)||0)+d); if(sq>0) nv=Math.min(nv,sq); el.value=nv; recalc(); }

function buildAll(){
  var cats = [];
  P.forEach(function(p,i){ if(!deleted[i]&&!archived[i]&&cats.indexOf(p.cat)<0) cats.push(p.cat); });
  var cont = document.getElementById('pc');
  cont.innerHTML = '';
  var renderedCats = [];
  cats.forEach(function(cat){
    var prods = P.map(function(p,i){ return Object.assign({},p,{idx:i}); })
      .filter(function(p){ return p.cat===cat && !deleted[p.idx] && !archived[p.idx]; });
    if(!prods.length) return;
    renderedCats.push(cat);
    prods.sort(function(a,b){
      var aOk=avail[a.idx]?0:1, bOk=avail[b.idx]?0:1;
      if(aOk!==bOk) return aOk-bOk;
      return a.name.localeCompare(b.name,'cs');
    });
    var nok = prods.filter(function(p){ return avail[p.idx]; }).length;
    var cards = '';
    prods.forEach(function(p){
      var ok = avail[p.idx];
      var warm = p.sklad.indexOf('18')>=0 || p.sklad.indexOf('25')>=0;
      var tagCls = warm ? 'tag-warm' : 'tag-cold';
      var meta = '';
      if(p.baleni) meta += '<span>'+p.baleni+'</span>';
      if(p.trv) meta += '<span>'+p.trv+'</span>';
      cards += '<div class="prod-card'+(ok?'':' unavail')+'">'
        +'<div class="prod-card-name">'+p.name+'</div>'
        +'<div class="prod-card-tags">'
          +'<span class="ptag '+tagCls+'">'+p.sklad+'</span>'
          +(ok?'':'<span class="prod-na-badge">Nedostupné</span>')
        +'</div>'
        +(meta?'<div class="prod-card-meta">'+meta+'</div>':'')
        +(p.vahy
          ? '<div class="prod-card-price">'+p.voc+' Kč<span class="prod-price-per"> / ks</span></div>'
            +'<div class="prod-vahy-sub"><span class="prod-vahy-kg">'+p.voc_kg+' Kč/kg</span><span class="vahy-badge">vážený produkt</span></div>'
          : '<div class="prod-card-price">'+p.voc+' Kč<span class="prod-price-per"> / ks</span></div>')
        +(ok?(function(){
            var sq=stockQty[p.idx]||0;
            var maxAttr=sq>0?' max="'+sq+'"':'';
            var stockBadge=sq>0?'<span style="font-size:11px;font-weight:700;color:#c0522a;background:rgba(192,82,42,.1);border-radius:6px;padding:2px 7px;">Zbývá '+sq+' ks</span>':'';
            return '<div style="display:flex;align-items:center;justify-content:space-between;gap:4px;margin-top:2px;">'+stockBadge+'</div>'
              +'<div class="prod-card-qty-row"><button class="qty-btn" onclick="changeQty('+p.idx+',-1)">−</button><input class="qty-inp" type="number" min="0" step="1" value="0"'+maxAttr+' id="q'+p.idx+'" oninput="recalc()"><button class="qty-btn" onclick="changeQty('+p.idx+',1)">+</button></div>';
          })():'')
        +'<div class="prod-card-total" id="l'+p.idx+'"></div>'
        +'</div>';
    });
    var block = document.createElement('div');
    block.className = 'cat-block';
    block.innerHTML = '<div class="cat-hd"><span class="cat-name">'+cat+'</span><span class="cat-cnt">'+nok+' / '+prods.length+' skladem</span></div>'
      +'<div class="prod-grid">'+cards+'</div>';
    cont.appendChild(block);
  });
  recalc();
  _buildCatNav(renderedCats);
  _watchCatScroll();
}

function _buildCatNav(cats){
  var nav = document.getElementById('cat-nav');
  if(!nav) return;
  nav.innerHTML = cats.map(function(c, i){
    return '<button class="cat-nav-tab" type="button" onclick="_jumpToCat('+i+')">'+_he(c)+'</button>';
  }).join('');
}

function _jumpToCat(i){
  var blocks = document.querySelectorAll('#pc > .cat-block');
  var b = blocks[i];
  if(!b) return;
  var navH = (document.getElementById('cat-nav')||{}).offsetHeight || 0;
  var top = b.getBoundingClientRect().top + window.scrollY - navH - 12;
  window.scrollTo({ top: top, behavior: 'smooth' });
}

function _watchCatScroll(){
  var blocks = document.querySelectorAll('#pc > .cat-block');
  var tabs = document.querySelectorAll('.cat-nav-tab');
  if(!blocks.length || !tabs.length) return;
  var pending = false;
  function update(){
    pending = false;
    var navH = (document.getElementById('cat-nav')||{}).offsetHeight || 0;
    var y = window.scrollY + navH + 24;
    var activeIdx = 0;
    for(var i=0;i<blocks.length;i++){
      if(blocks[i].offsetTop <= y) activeIdx = i; else break;
    }
    for(var j=0;j<tabs.length;j++){
      if(j===activeIdx) tabs[j].classList.add('active');
      else tabs[j].classList.remove('active');
    }
  }
  function onScroll(){
    if(pending) return;
    pending = true;
    requestAnimationFrame(update);
  }
  if(window._dfCatScrollHandler) window.removeEventListener('scroll', window._dfCatScrollHandler);
  window._dfCatScrollHandler = onScroll;
  window.addEventListener('scroll', onScroll, { passive: true });
  update();
}

function recalc(){
  var total = 0, items = [];
  P.forEach(function(p,i){
    var el = document.getElementById('q'+i);
    if(!el) return;
    var q = Math.max(0, parseInt(el.value)||0);
    var lel = document.getElementById('l'+i);
    if(q>0){
      var val = p.voc*q; total+=val;
      if(lel) lel.textContent = fmt(val);
      items.push(Object.assign({},p,{qty:q,total:val}));
    } else { if(lel) lel.textContent='—'; }
  });
  document.getElementById('tv').textContent = fmt(total);
  var dph = total * VAT;
  document.getElementById('tsdph').innerHTML = total>0
    ? '<span>Celkem s DPH: <strong>'+fmt(total*(1+VAT))+'</strong></span>'
    : '';
  // floating bar
  var fb=document.getElementById('float-bar');
  if(fb){
    if(total>0){
      var totalQty=items.reduce(function(s,it){return s+it.qty;},0);
      document.getElementById('float-cnt').textContent=totalQty+' ks';
      document.getElementById('float-amt').textContent=fmt(total);
      fb.classList.add('show');
    } else { fb.classList.remove('show'); }
  }
  var sb = document.getElementById('sb');
  if(!items.length){
    sb.innerHTML='<div class="sum-empty">Zatím nebyl vybrán žádný produkt.</div>';
    return;
  }
  var irows = '';
  items.forEach(function(it){
    var n = it.name+(it.baleni?' ('+it.baleni+')':'');
    irows += '<div class="srow"><span class="sn">'+n+' \u00d7 '+it.qty+' ks</span><span class="sv">'+fmt(it.total)+'</span></div>';
  });
  sb.innerHTML = '<div class="sum-items">'+irows+'</div>'
    +'<div class="sum-sub"><span>DPH 12 %</span><span>'+fmt(dph)+'</span></div>';
}

function potvrditObjednavku(){
  var jm=document.getElementById('jmeno').value.trim();
  var em=document.getElementById('email').value.trim();
  if(!jm||!em){ alert('Vyplňte prosím jméno a e-mail.'); return; }
  var items=[];
  P.forEach(function(p,i){
    var el=document.getElementById('q'+i); if(!el) return;
    var q=Math.max(0,parseInt(el.value)||0);
    if(q>0) items.push(Object.assign({},p,{qty:q,total:p.voc*q}));
  });
  if(!items.length){ alert('Přidejte prosím alespoň jeden produkt.'); return; }
  var tb=items.reduce(function(s,i){return s+i.total;},0);
  var fi=document.getElementById('firma').value.trim();
  var tel=document.getElementById('tel').value.trim();
  var adr=document.getElementById('adr').value.trim();
  var poz=document.getElementById('poz').value.trim();

  var btn=document.querySelector('.send-btn');
  if(btn){ btn.disabled=true; btn.textContent='Odesílám…'; }

  _db.from('orders').insert([{
    customer_name: jm,
    company: fi||null,
    email: em,
    phone: tel||null,
    address: adr||null,
    note: poz||null,
    items: items.map(function(it){ return {name:it.name,baleni:it.baleni||'',qty:it.qty,voc:it.voc,total:it.total}; }),
    total_without_vat: tb,
    user_id: _user ? _user.id : null
  }]).then(function(res){
    if(btn){ btn.disabled=false; btn.textContent='Potvrdit objednávku →'; }
    if(res.error){ alert('Nepodařilo se odeslat objednávku. Zkuste to prosím znovu.\n('+res.error.message+')'); return; }
    // Zapamatovat zákazníka
    saveCustomerDetails(jm,fi,em,tel,adr);
    // Email notifikace
    if(EJS_KEY){
      var itemsTxt=items.map(function(it){ return it.name+(it.baleni?' ('+it.baleni+')':'')+' — '+it.qty+' ks — '+it.total.toFixed(2)+' Kc'; }).join('\n');
      emailjs.send(EJS_SERVICE, EJS_TEMPLATE, {
        customer_name: jm, company: fi||'—', email: em, phone: tel||'—',
        items_text: itemsTxt, total: tb.toFixed(2), note: poz||'—'
      }).catch(function(e){ console.warn('EmailJS:', e); });
    }
    // Zobrazit potvrzení
    var rows='<div class="confirm-row"><span class="cl">Zákazník</span><span class="cv">'+jm+'</span></div>';
    if(fi) rows+='<div class="confirm-row"><span class="cl">Firma</span><span class="cv">'+fi+'</span></div>';
    rows+='<div class="confirm-row"><span class="cl">Položek</span><span class="cv">'+items.length+' '+(items.length===1?'druh':items.length<5?'druhy':'druhů')+'</span></div>';
    rows+='<div class="confirm-row"><span class="cl">Celkem bez DPH</span><span class="cv">'+tb.toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kč</span></div>';
    document.getElementById('confirm-detail').innerHTML=rows;
    document.getElementById('confirm-modal').className='show';
  });
}

function closeConfirm(){
  document.getElementById('confirm-modal').className='';
  document.getElementById('poz').value='';
  P.forEach(function(p,i){ var el=document.getElementById('q'+i); if(el) el.value=0; });
  // Refill saved customer details if remember-me is on
  try{
    var saved=localStorage.getItem('df_customer');
    if(saved){ var c=JSON.parse(saved); ['jmeno','firma','email','tel','adr'].forEach(function(id){ var el=document.getElementById(id); if(el) el.value=c[id]||''; }); }
    else { ['jmeno','firma','email','tel','adr'].forEach(function(id){ var el=document.getElementById(id); if(el) el.value=''; }); }
  }catch(e){}
  recalc();
}

function toggleRemember(){
  var on=document.getElementById('remember-me').checked;
  document.getElementById('forget-link').style.display=on?'inline':'none';
  if(!on) localStorage.removeItem('df_customer');
}
function saveCustomerDetails(jm,fi,em,tel,adr){
  if(!document.getElementById('remember-me').checked) return;
  try{ localStorage.setItem('df_customer',JSON.stringify({jmeno:jm,firma:fi,email:em,tel:tel,adr:adr})); }catch(e){}
}
function forgetMe(){
  localStorage.removeItem('df_customer');
  document.getElementById('remember-me').checked=false;
  document.getElementById('forget-link').style.display='none';
}

function odeslat(){
  var jm = document.getElementById('jmeno').value.trim();
  var em = document.getElementById('email').value.trim();
  if(!jm||!em){ alert('Vyplňte prosím jméno a e-mail.'); return; }
  var items=[];
  P.forEach(function(p,i){
    var el=document.getElementById('q'+i); if(!el) return;
    var q=Math.max(0,parseInt(el.value)||0);
    if(q>0) items.push(Object.assign({},p,{qty:q,total:p.voc*q}));
  });
  if(!items.length){ alert('Přidejte prosím alespoň jeden produkt.'); return; }

  // generate & download PDF first
  generatePDF();

  var tb=items.reduce(function(s,i){return s+i.total;},0);
  var datum=new Date().toLocaleDateString('cs-CZ');
  var fi=document.getElementById('firma').value.trim();
  var tel=document.getElementById('tel').value.trim();
  var adr=document.getElementById('adr').value.trim();
  var poz=document.getElementById('poz').value.trim();
  // Uložit do Supabase
  _db.from('orders').insert([{
    customer_name: jm,
    company: fi||null,
    email: em,
    phone: tel||null,
    address: adr||null,
    note: poz||null,
    items: items.map(function(it){ return {name:it.name,baleni:it.baleni||'',qty:it.qty,voc:it.voc,total:it.total}; }),
    total_without_vat: tb,
    user_id: _user ? _user.id : null
  }]).then(function(res){ if(res.error) console.warn('Supabase insert error:', res.error.message); });

  var subj='Objednávka – '+jm+(fi?' / '+fi:'')+' – '+datum;
  var body='OBJEDNÁVKA – DIVOKÉ FARMY\n';
  body+='══════════════════════════════\n';
  body+='Datum: '+datum+'\n';
  body+='Zákazník: '+jm+'\n';
  if(fi) body+='Firma: '+fi+'\n';
  body+='E-mail: '+em+'\n';
  if(tel) body+='Telefon: '+tel+'\n';
  if(adr) body+='Adresa: '+adr+'\n';
  body+='\nOBJEDNANÉ ZBOŽÍ:\n';
  body+='──────────────────────────────\n';
  items.forEach(function(it){
    body+=it.name+(it.baleni?' ('+it.baleni+')':'')+'\n';
    body+='  Množství: '+it.qty+' ks  |  VOC/ks: '+it.voc+' Kč  |  Celkem: '+it.total.toFixed(2)+' Kč\n';
  });
  body+='──────────────────────────────\n';
  body+='Celkem bez DPH: '+tb.toFixed(2)+' Kč\n';
  body+='DPH 12 %:       '+(tb*VAT).toFixed(2)+' Kč\n';
  body+='Celkem s DPH:   '+(tb*(1+VAT)).toFixed(2)+' Kč\n';
  if(poz) body+='\nPoznámka: '+poz+'\n';
  body+='\n* Cena orientační, skutečná cena u váženého zboží bude upřesněna.';
  setTimeout(function(){
    window.location.href='mailto:'+EMAIL_TO+'?subject='+encodeURIComponent(subj)+'&body='+encodeURIComponent(body);
    setTimeout(function(){ showPdfNotice(); }, 800);
  }, 400);
}

function showPdfNotice(){
  var n=document.getElementById('pdf-notice');
  if(!n) return;
  n.style.display='flex';
  setTimeout(function(){ n.style.opacity='1'; },10);
  setTimeout(function(){ n.style.opacity='0'; setTimeout(function(){n.style.display='none';},400); },6000);
}

// PASSWORD
// ── Admin access (Supabase Auth + RLS) ──
// The UI gate below is UX only. Real protection lives in Supabase RLS:
// the `is_admin()` policies refuse non-admin writes even if a user opens
// the admin overlay via DevTools. See supabase/migrations/01_admin_rls.sql.
var _adminPendingOpen = false;
function _isAdmin(){
  return !!(_user && _user.app_metadata && _user.app_metadata.role === 'admin');
}
function requestAdminAccess(){
  if(_isAdmin()){ openAdmin(); return; }
  if(_user){
    alert('Tento účet nemá administrátorská oprávnění.\nPřihlaste se prosím účtem správce.');
    return;
  }
  _adminPendingOpen = true;
  openAuthModal('login');
}

// ── ADMIN ──
function openAdmin(){
  switchTab('products');
  renderAdmin('');
  document.getElementById('adm-ov').style.display='block';
}
function closeAdmin(){ document.getElementById('adm-ov').style.display='none'; }

function switchTab(tab){
  ['products','orders','dl'].forEach(function(t){
    var btn=document.getElementById('tab-'+t);
    var pane=document.getElementById('pane-'+t);
    if(btn) btn.classList.toggle('active', t===tab);
    if(pane) pane.style.display = t===tab ? 'block' : 'none';
  });
  if(tab==='orders') loadOrders();
  if(tab==='dl') loadDodaciListy();
}

// ── Orders ──
var _orders = [];
function loadOrders(){
  document.getElementById('orders-list').innerHTML = '<div class="orders-msg">Načítám objednávky…</div>';
  _db.from('orders').select('*').order('created_at',{ascending:false}).then(function(res){
    if(res.error){ document.getElementById('orders-list').innerHTML='<div class="orders-msg">Chyba: '+res.error.message+'</div>'; return; }
    _orders = res.data || [];
    renderOrders();
  });
}

function renderOrders(){
  var list = document.getElementById('orders-list');
  if(!_orders.length){ list.innerHTML='<div class="orders-msg">Zatím žádné objednávky.</div>'; return; }
  var stLabel={nova:'Nová',vyrizuje_se:'Vyřizuje se',vyrizena:'Vyřízena',storno:'Storno',archivovana:'Archivováno'};
  var stCls={nova:'st-nova',vyrizuje_se:'st-vyrizuje',vyrizena:'st-vyrizena',storno:'st-storno',archivovana:'st-archivovana'};
  var html='<div class="orders-list">';
  _orders.forEach(function(o,idx){
    var d=new Date(o.created_at).toLocaleDateString('cs-CZ');
    var st=o.status||'nova';
    var items=o.items||[];
    var irows='';
    items.forEach(function(it){
      irows+='<tr><td>'+(it.name||'')+(it.baleni?' ('+it.baleni+')':'')+'</td><td style="text-align:center">'+it.qty+' ks</td><td style="text-align:right;font-weight:800">'+it.total.toFixed(2)+' Kč</td></tr>';
    });
    var info='';
    if(o.company) info+='<strong>'+o.company+'</strong> · ';
    info+=o.email;
    if(o.phone) info+=' · '+o.phone;
    if(o.address) info+='<br>'+o.address;
    if(o.note) info+='<br><em>'+o.note+'</em>';
    var isStorno = st==='storno';
    html+='<div class="order-card'+(isStorno?' storno-card':'')+'" id="oc'+idx+'">'
      +'<div class="order-hd" onclick="toggleOrder('+idx+')">'
        +'<span class="order-date">'+d+'</span>'
        +'<span class="order-name">'+o.customer_name+(o.company?'<br><small style="font-size:11px;font-weight:500;opacity:.65;letter-spacing:0">'+o.company+'</small>':'')+'</span>'
        +'<span class="order-total">'+o.total_without_vat.toFixed(2)+' Kč</span>'
        +'<span class="order-status '+(stCls[st]||'st-nova')+'" id="ostlbl'+idx+'">'+(stLabel[st]||'Nová')+'</span>'
      +'</div>'
      +'<div class="order-body" id="ob'+idx+'">'
        +'<div class="order-info">'+info+'</div>'
        +'<table class="order-items-tbl"><tr><th>Produkt</th><th style="text-align:center">Množství</th><th style="text-align:right">Celkem</th></tr>'+irows+'</table>'
        +'<div class="order-actions">'
          +'<button class="st-btn'+(st==='nova'?' act':'')+'" onclick="setOrderStatus(\''+o.id+'\','+idx+',\'nova\')">Nová</button>'
          +'<button class="st-btn'+(st==='vyrizuje_se'?' act':'')+'" onclick="setOrderStatus(\''+o.id+'\','+idx+',\'vyrizuje_se\')">Vyřizuje se</button>'
          +'<button class="st-btn'+(st==='vyrizena'?' act':'')+'" onclick="setOrderStatus(\''+o.id+'\','+idx+',\'vyrizena\')">Vyřízena</button>'
          +'<button class="order-pdf-btn" onclick="tiskniObjednavkuPDF('+idx+')">🖨 PDF</button>'
          +'<button class="dl-make-btn" onclick="openDodaciList('+idx+')">📄 Dodací list</button>'
          +'<button class="danger-btn" onclick="stornujObjednavku(\''+o.id+'\','+idx+')">⊘ Storno</button>'
          +'<button class="muted-btn" onclick="archivujObjednavku(\''+o.id+'\','+idx+')">📦 Archivovat</button>'
          +'<button class="danger-btn" style="border-color:rgba(100,0,0,0.3);background:rgba(100,0,0,0.07);color:#800" onclick="smazatObjednavku(\''+o.id+'\','+idx+')">🗑 Smazat</button>'
        +'</div>'
      +'</div>'
    +'</div>';
  });
  html+='</div>';
  list.innerHTML=html;
}

function toggleOrder(idx){
  document.getElementById('ob'+idx).classList.toggle('show');
}

function setOrderStatus(id,idx,status){
  var stLabel={nova:'Nová',vyrizuje_se:'Vyřizuje se',vyrizena:'Vyřízena',storno:'Storno',archivovana:'Archivováno'};
  var stCls={nova:'st-nova',vyrizuje_se:'st-vyrizuje',vyrizena:'st-vyrizena',storno:'st-storno',archivovana:'st-archivovana'};
  _db.from('orders').update({status:status}).eq('id',id).then(function(res){
    if(res.error){ alert('Chyba při ukládání stavu: '+res.error.message+'\n\nSpusť v Supabase SQL Editor:\nCREATE POLICY "admin_update_orders" ON orders FOR UPDATE TO authenticated USING (true) WITH CHECK (true);'); return; }
    _orders[idx].status=status;
    var lbl=document.getElementById('ostlbl'+idx);
    if(lbl){ lbl.textContent=stLabel[status]; lbl.className='order-status '+(stCls[status]||'st-nova'); }
    var card=document.getElementById('oc'+idx);
    if(card){
      var btns=card.querySelectorAll('.st-btn');
      var sts=['nova','vyrizuje_se','vyrizena'];
      btns.forEach(function(btn,bi){ btn.classList.toggle('act',sts[bi]===status); });
    }
  });
}
function stornujObjednavku(id,idx){
  if(!confirm('Opravdu stornovat tuto objednávku?')) return;
  _db.from('orders').update({status:'storno'}).eq('id',id).then(function(res){
    if(res.error){ alert('Chyba: '+res.error.message); return; }
    _orders[idx].status='storno';
    renderOrders();
  });
}
function archivujObjednavku(id,idx){
  _db.from('orders').update({status:'archivovana'}).eq('id',id).then(function(res){
    if(res.error){ alert('Chyba: '+res.error.message); return; }
    _orders[idx].status='archivovana';
    renderOrders();
  });
}
function smazatObjednavku(id,idx){
  if(!confirm('Opravdu trvale smazat tuto objednávku? Tato akce je nevratná.')) return;
  _db.from('orders').delete().eq('id',id).then(function(res){
    if(res.error){ alert('Chyba při mazání: '+res.error.message+'\n\nPokud se objednávka vrátí po obnovení, spusť v Supabase SQL Editor:\nCREATE POLICY "admin_delete_orders" ON orders FOR DELETE TO authenticated USING (true);'); return; }
    _orders=_orders.filter(function(o){ return o.id!==id; });
    renderOrders();
  });
}
function tiskniObjednavkuPDF(idx){
  var o=_orders[idx]; if(!o) return;
  var items=o.items||[];
  var datum=new Date(o.created_at).toLocaleDateString('cs-CZ');
  var ordNum='OBJ-'+o.id.toString().slice(-6).toUpperCase();
  var bez=o.total_without_vat||0, dph=bez*VAT, celk=bez*(1+VAT);
  function esc(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  var rows=items.map(function(it,i){
    return '<tr>'
      +'<td class="c">'+( i+1)+'</td>'
      +'<td>'+esc(it.name)+'</td>'
      +'<td class="c">'+esc(it.baleni||'—')+'</td>'
      +'<td class="c">'+it.qty+' ks</td>'
      +'<td class="r">'+(it.voc||0).toFixed(2)+' Kč</td>'
      +'<td class="r b">'+it.total.toFixed(2)+' Kč</td>'
      +'</tr>';
  }).join('');
  var info='<strong>'+esc(o.customer_name)+'</strong>';
  if(o.company) info+='<br>'+esc(o.company);
  info+='<br>Email: '+esc(o.email);
  if(o.phone) info+='<br>Tel: '+esc(o.phone);
  if(o.address) info+='<br>Adresa: '+esc(o.address);
  var html='<!DOCTYPE html><html lang="cs"><head><meta charset="UTF-8"><title>'+ordNum+'</title>'
    +'<style>'
    +'*{margin:0;padding:0;box-sizing:border-box;}'
    +'body{font-family:Arial,Helvetica,sans-serif;font-size:10pt;color:#111;}'
    +'@page{margin:14mm 14mm 20mm 14mm;}'
    +'.hd{display:flex;justify-content:space-between;align-items:center;background:#111;color:#fff;padding:9px 14px;margin-bottom:18px;}'
    +'.hd-co{font-size:15pt;font-weight:bold;letter-spacing:.5px;}'
    +'.hd-ct{font-size:7.5pt;text-align:right;line-height:1.5;}'
    +'.title{font-size:20pt;font-weight:bold;margin-bottom:3px;}'
    +'.sub{font-size:9pt;color:#555;margin-bottom:14px;}'
    +'hr.thick{border:none;border-top:1.5px solid #111;margin:10px 0;}'
    +'hr.thin{border:none;border-top:.5px solid #bbb;margin:10px 0;}'
    +'.lbl{font-size:7pt;font-weight:bold;color:#777;letter-spacing:.8px;text-transform:uppercase;margin-bottom:5px;}'
    +'.cust{font-size:10pt;line-height:1.65;margin-bottom:14px;}'
    +'table{width:100%;border-collapse:collapse;margin-top:4px;}'
    +'th{background:#111;color:#fff;font-size:8.5pt;padding:6px 8px;text-align:left;font-weight:bold;}'
    +'td{font-size:10pt;padding:6px 8px;border-bottom:.5px solid #ddd;}'
    +'tr:nth-child(even) td{background:#f4f4f4;}'
    +'.c{text-align:center;} .r{text-align:right;} .b{font-weight:bold;}'
    +'.tots{display:flex;justify-content:flex-end;margin-top:14px;}'
    +'.tots table{width:250px;border-collapse:collapse;}'
    +'.tots td{font-size:10pt;padding:3px 8px;border:none;}'
    +'.tots .fin{font-size:12pt;font-weight:bold;border-top:1.5px solid #111;padding-top:5px;}'
    +'.note{margin-top:14px;padding:9px 11px;border:1px solid #ccc;font-size:9pt;font-style:italic;color:#444;}'
    +'.ft{position:fixed;bottom:0;left:0;right:0;background:#111;color:#ccc;text-align:center;font-size:7pt;padding:5px;}'
    +'</style></head><body>'
    +'<div class="hd"><div class="hd-co">DIVOKÉ FARMY</div>'
    +'<div class="hd-ct">divokefarmy.cz &nbsp;|&nbsp; adam@divokefarmy.cz &nbsp;|&nbsp; +420 777 186 246</div></div>'
    +'<div class="title">OBJEDNÁVKA</div>'
    +'<div class="sub">'+ordNum+'&ensp;|&ensp;'+datum+'</div>'
    +'<hr class="thick">'
    +'<div class="lbl">Zákazník</div>'
    +'<div class="cust">'+info+'</div>'
    +'<hr class="thin">'
    +'<div class="lbl">Položky objednávky</div>'
    +'<table><thead><tr>'
    +'<th style="width:24px">#</th><th>Produkt</th>'
    +'<th style="width:68px;text-align:center">Balení</th>'
    +'<th style="width:62px;text-align:center">Množství</th>'
    +'<th style="width:94px;text-align:right">VOC bez DPH&nbsp;/&nbsp;ks</th>'
    +'<th style="width:94px;text-align:right">Celkem bez DPH</th>'
    +'</tr></thead><tbody>'+rows+'</tbody></table>'
    +'<div class="tots"><table>'
    +'<tr><td>Celkem bez DPH:</td><td class="r">'+bez.toFixed(2)+' Kč</td></tr>'
    +'<tr><td>DPH 12&nbsp;%:</td><td class="r">'+dph.toFixed(2)+' Kč</td></tr>'
    +'<tr class="fin"><td><strong>CELKEM S DPH:</strong></td><td class="r b">'+celk.toFixed(2)+' Kč</td></tr>'
    +'</table></div>'
    +(o.note?'<div class="note"><strong>Poznámka:</strong> '+esc(o.note)+'</div>':'')
    +'<div class="ft">DF obchodní s.r.o.&ensp;|&ensp;IČO: 29279313&ensp;|&ensp;Šebrov 195, 679 22 Lipůvka&ensp;|&ensp;divokefarmy.cz</div>'
    +'</body></html>';
  var blob=new Blob([html],{type:'text/html'});
  var blobUrl=URL.createObjectURL(blob);
  var win=window.open(blobUrl,'_blank','width=820,height=960');
  win.focus();
  setTimeout(function(){ win.print(); URL.revokeObjectURL(blobUrl); },500);
}

function saveAdmin(keepOpen){
  _saveProductState();
  if(!keepOpen){ closeAdmin(); }
}

function renderAdmin(q){
  var cats=[];
  P.forEach(function(p,i){ if(!deleted[i]&&cats.indexOf(p.cat)<0) cats.push(p.cat); });
  var html='', ql=q.toLowerCase();
  cats.forEach(function(cat){
    var prods=P.map(function(p,i){return Object.assign({},p,{idx:i});})
      .filter(function(p){ return p.cat===cat&&!deleted[p.idx]&&(!ql||p.name.toLowerCase().indexOf(ql)>=0); });
    if(!prods.length) return;
    html+='<div class="adm-cat"><div class="adm-clabel">'+cat+'</div>';
    prods.forEach(function(p){
      var i=p.idx, ok=!!avail[i], isArch=!!archived[i];
      var esc=function(v){return (v||'').replace(/"/g,'&quot;');};
      html+='<div class="adm-item">'
        +'<div class="adm-row'+(isArch?' archived-row':'')+'" id="admrow'+i+'">'
          +'<span class="adm-pname" id="admpn'+i+'">'+p.name+(isArch?' <em style="font-size:10px;opacity:.6">(archiv)</em>':'')+'</span>'
          +'<span class="adm-bal" id="admbl'+i+'">'+(p.baleni||'')+'</span>'
          +(isArch
            ?'<span class="apill ap-arch">Archivováno</span>'
            :'<span class="apill '+(ok?'ap-ok':'ap-no')+'" id="ap'+i+'">'+(ok?'Skladem':'Nedostupné')+'</span>'
              +(stockQty[i]>0?'<span class="adm-stock-badge" id="admsb'+i+'">Zbývá '+stockQty[i]+' ks</span>':'<span class="adm-stock-badge" id="admsb'+i+'" style="display:none"></span>')
              +'<label class="tgl"><input type="checkbox" '+(ok?'checked':'')+' onchange="tog('+i+',this.checked)"><span class="tsl"></span></label>'
          )
          +'<div class="adm-item-actions">'
            +'<button class="adm-edit-btn" id="admbtn'+i+'" onclick="toggleEdit('+i+')">✎ Upravit</button>'
            +'<button class="adm-arch-btn" onclick="archiveProd('+i+')">'+(isArch?'Obnovit':'Archivovat')+'</button>'
            +'<button class="adm-del-btn" onclick="deleteProd('+i+')">Smazat</button>'
          +'</div>'
        +'</div>'
        +'<div class="adm-edit" id="admedit'+i+'">'
          +'<div class="adm-edit-grid">'
            +'<div class="adm-ef full"><label>Název produktu</label><input id="adn'+i+'" value="'+esc(p.name)+'"></div>'
            +'<div class="adm-ef"><label>VOC cena za kus (Kč bez DPH)</label><input type="number" id="adv'+i+'" value="'+p.voc+'"></div>'
            +'<div class="adm-ef"><label>Balení / Objem</label><input id="adb'+i+'" value="'+esc(p.baleni)+'"></div>'
            +'<div class="adm-ef"><label>Skladování</label><input id="ads'+i+'" value="'+esc(p.sklad)+'"></div>'
            +'<div class="adm-ef"><label>Trvanlivost</label><input id="adt'+i+'" value="'+esc(p.trv)+'"></div>'
            +'<div class="adm-ef"><label>Počet kusů skladem <span style="font-weight:400;font-size:11px;opacity:.65">(0 = neomezeno)</span></label><input type="number" id="adstock'+i+'" min="0" value="'+(stockQty[i]||0)+'"></div>'
            +'<div class="adm-ef adm-vahy-row"><label class="adm-vahy-label"><input type="checkbox" id="advahy'+i+'" '+(p.vahy?'checked':'')+' onchange="toggleVahyKg('+i+',this.checked)"> Vážený produkt (fakturace dle kg)</label></div>'
            +'<div class="adm-ef" style="'+(p.vahy?'':'display:none')+'" id="advefdlkg'+i+'"><label>VOC cena za kg (Kč/kg bez DPH)</label><input type="number" id="advkg'+i+'" value="'+(p.voc_kg||0)+'"></div>'
          +'</div>'
          +'<button class="adm-prod-save" onclick="saveProd('+i+')">Uložit změny</button>'
        +'</div>'
        +'</div>';
    });
    html+='</div>';
  });
  document.getElementById('adm-list').innerHTML=html||'<p style="color:#837261;font-size:13px;padding:10px 0;">Nic nenalezeno.</p>';
}

function tog(i,v){
  avail[i]=v;
  var el=document.getElementById('ap'+i);
  if(el){el.textContent=v?'Skladem':'Nedostupné';el.className='apill '+(v?'ap-ok':'ap-no');}
  _saveProductState();
}
function _saveProductState(){
  var customs=P.filter(function(p){return p._custom;}).map(function(p){
    return {cat:p.cat,name:p.name,baleni:p.baleni,sklad:p.sklad,trv:p.trv,voc:p.voc,ok:p.ok};
  });
  try{
    localStorage.setItem('df_av',JSON.stringify(avail));
    localStorage.setItem('df_po',JSON.stringify(prodOverrides));
    localStorage.setItem('df_arch',JSON.stringify(archived));
    localStorage.setItem('df_del',JSON.stringify(deleted));
    localStorage.setItem('df_cp',JSON.stringify(customs));
    localStorage.setItem('df_sq',JSON.stringify(stockQty));
  }catch(e){}
  _db.from('product_state').upsert([{
    id:1, avail:avail, overrides:prodOverrides, archived:archived, deleted:deleted,
    custom_prods:customs, updated_at:new Date().toISOString()
  }]).then(function(res){ if(res.error) console.warn('Product sync error:',res.error.message); });
  buildAll();
}
function toggleEdit(i){
  var edit=document.getElementById('admedit'+i),btn=document.getElementById('admbtn'+i),row=document.getElementById('admrow'+i);
  var open=edit.classList.contains('show');
  edit.classList.toggle('show',!open);
  btn.classList.toggle('open',!open);
  btn.textContent=open?'✎ Upravit':'✕ Zavřít';
  row.style.borderRadius=open?'12px':'12px 12px 0 0';
}
function toggleVahyKg(i, checked){
  var el=document.getElementById('advefdlkg'+i);
  if(el) el.style.display=checked?'':'none';
}
function saveProd(i){
  var name=document.getElementById('adn'+i).value.trim()||P[i].name;
  var voc=parseFloat(document.getElementById('adv'+i).value)||P[i].voc;
  var baleni=document.getElementById('adb'+i).value.trim();
  var sklad=document.getElementById('ads'+i).value.trim();
  var trv=document.getElementById('adt'+i).value.trim();
  var vahyEl=document.getElementById('advahy'+i);
  var vahy=vahyEl?vahyEl.checked:P[i].vahy;
  var voc_kg=parseFloat(document.getElementById('advkg'+i).value)||0;
  var stockEl=document.getElementById('adstock'+i);
  var stock=stockEl?Math.max(0,parseInt(stockEl.value)||0):0;
  P[i].name=name;P[i].voc=voc;P[i].baleni=baleni;P[i].sklad=sklad;P[i].trv=trv;P[i].vahy=vahy;P[i].voc_kg=voc_kg;
  prodOverrides[i]={name:name,voc:voc,baleni:baleni,sklad:sklad,trv:trv,vahy:vahy,voc_kg:voc_kg,stock:stock};
  if(stock>0){ stockQty[i]=stock; } else { delete stockQty[i]; }
  var pn=document.getElementById('admpn'+i);if(pn)pn.textContent=name;
  var bl=document.getElementById('admbl'+i);if(bl)bl.textContent=baleni;
  toggleEdit(i);
}
function archiveProd(i){
  archived[i]=!archived[i];
  renderAdmin(document.getElementById('adm-srch').value);
}
function deleteProd(i){
  if(!confirm('Opravdu smazat produkt "'+P[i].name+'"? Tuto akci nelze vrátit zpět.')) return;
  deleted[i]=true;
  renderAdmin(document.getElementById('adm-srch').value);
}
function toggleAddForm(){
  var f=document.getElementById('adm-add-form');
  f.classList.toggle('show');
  if(f.classList.contains('show')){
    document.getElementById('anew-name').focus();
  } else {
    ['anew-name','anew-voc','anew-baleni','anew-sklad','anew-trv','anew-voc-kg'].forEach(function(id){
      var el=document.getElementById(id);if(el)el.value='';
    });
    document.getElementById('anew-cat').value='';
    var vahyEl=document.getElementById('anew-vahy');if(vahyEl)vahyEl.checked=false;
    var kgRow=document.getElementById('anew-voc-kg-row');if(kgRow)kgRow.style.display='none';
  }
}
function addProd(){
  var name=document.getElementById('anew-name').value.trim();
  var cat=document.getElementById('anew-cat').value;
  var voc=parseFloat(document.getElementById('anew-voc').value)||0;
  var baleni=document.getElementById('anew-baleni').value.trim();
  var sklad=document.getElementById('anew-sklad').value.trim();
  var trv=document.getElementById('anew-trv').value.trim();
  var vahyEl=document.getElementById('anew-vahy');
  var vahy=vahyEl?vahyEl.checked:false;
  var voc_kg=parseFloat(document.getElementById('anew-voc-kg').value)||0;
  if(!name||!cat||!voc){alert('Vyplňte prosím název, kategorii a cenu.');return;}
  var np={cat:cat,name:name,baleni:baleni,sklad:sklad||'lednice',trv:trv,voc:voc,ok:true,_custom:true,vahy:vahy,voc_kg:voc_kg};
  P.push(np);
  customProds.push(np);
  avail[P.length-1]=true;
  toggleAddForm();
  renderAdmin(document.getElementById('adm-srch').value);
}
document.getElementById('adm-srch').addEventListener('input',function(){renderAdmin(this.value);});

// ── PDF ──
function generatePDF(){
  var jm=document.getElementById('jmeno').value.trim();
  var em=document.getElementById('email').value.trim();
  if(!jm||!em){alert('Vyplňte prosím jméno a e-mail.');return;}
  var items=[];
  P.forEach(function(p,i){
    var el=document.getElementById('q'+i);if(!el)return;
    var q=Math.max(0,parseInt(el.value)||0);
    if(q>0)items.push(Object.assign({},p,{qty:q,total:p.voc*q}));
  });
  if(!items.length){alert('Přidejte prosím alespoň jeden produkt.');return;}
  var tb=items.reduce(function(s,it){return s+it.total;},0);
  var datum=new Date().toLocaleDateString('cs-CZ');
  var fi=document.getElementById('firma').value.trim();
  var tel=document.getElementById('tel').value.trim();
  var adr=document.getElementById('adr').value.trim();
  var poz=document.getElementById('poz').value.trim();

  var {jsPDF}=window.jspdf;
  var doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});

  // header bar
  doc.setFillColor(80,63,55);
  doc.rect(0,0,210,22,'F');
  doc.setTextColor(220,203,188);
  doc.setFontSize(14);doc.setFont('helvetica','bold');
  doc.text('DIVOKE FARMY',14,14);
  doc.setFontSize(9);doc.setFont('helvetica','normal');
  doc.text('Objednavka  |  '+datum,14,20);
  doc.text('DF obchodni s.r.o.  |  adam@divokefarmy.cz  |  +420 777 186 246',210-14,20,{align:'right'});

  // customer block
  doc.setTextColor(30,30,30);
  var y=32;
  doc.setFontSize(9);doc.setFont('helvetica','bold');
  doc.text('ZAKAZNIK',14,y);
  doc.setDrawColor(131,114,97);doc.setLineWidth(0.3);doc.line(14,y+2,90,y+2);
  y+=7;
  doc.setFont('helvetica','normal');
  var info=[jm];
  if(fi)info.push(fi);
  info.push('E-mail: '+em);
  if(tel)info.push('Telefon: '+tel);
  if(adr)info.push('Adresa: '+adr);
  info.forEach(function(l){doc.text(l,14,y);y+=5;});

  y+=4;
  // products table
  doc.autoTable({
    startY:y,
    head:[['Produkt','Objem','Trvanlivost','Skladovani','Mnozstvi','VOC/ks','Celkem']],
    body:items.map(function(it){return[
      it.name,
      it.baleni||'—',
      it.trv||'—',
      it.sklad||'—',
      it.qty+' ks',
      it.voc+' Kc',
      it.total.toFixed(2)+' Kc'
    ];}),
    headStyles:{fillColor:[80,63,55],textColor:[220,203,188],fontStyle:'bold',fontSize:8},
    bodyStyles:{fontSize:8,textColor:[30,30,30]},
    alternateRowStyles:{fillColor:[240,235,228]},
    columnStyles:{0:{cellWidth:55},4:{halign:'center'},5:{halign:'right'},6:{halign:'right',fontStyle:'bold'}},
    margin:{left:14,right:14},
    styles:{lineColor:[200,188,175],lineWidth:0.2}
  });

  var fy=doc.lastAutoTable.finalY+6;
  // totals
  doc.setFillColor(218,203,188);
  doc.rect(14,fy,182,22,'F');
  doc.setFontSize(9);doc.setFont('helvetica','normal');doc.setTextColor(131,114,97);
  doc.text('Celkem bez DPH:',120,fy+7);
  doc.text('DPH 12 %:',120,fy+13);
  doc.setFont('helvetica','bold');doc.setTextColor(30,30,30);
  doc.text(tb.toFixed(2)+' Kc',196,fy+7,{align:'right'});
  doc.text((tb*VAT).toFixed(2)+' Kc',196,fy+13,{align:'right'});
  doc.setFontSize(11);
  doc.text('CELKEM S DPH:',120,fy+21);
  doc.text((tb*(1+VAT)).toFixed(2)+' Kc',196,fy+21,{align:'right'});

  if(poz){
    var py=fy+30;
    doc.setFontSize(8);doc.setFont('helvetica','italic');doc.setTextColor(131,114,97);
    doc.text('Poznamka: '+poz,14,py,{maxWidth:182});
  }

  // footer
  doc.setFillColor(80,63,55);
  doc.rect(0,285,210,12,'F');
  doc.setFontSize(7.5);doc.setFont('helvetica','normal');doc.setTextColor(220,203,188);
  doc.text('DF obchodni s.r.o.  |  ICO: 29279313  |  Sebrov 195, 679 22 Lipuvka  |  divokefarmy.cz',105,292,{align:'center'});
  doc.text('* Cena orientacni, skutecna cena u vazeneho zbozi bude upresnena.',105,296,{align:'center'});

  var fn='objednavka-divokefarmy-'+datum.replace(/\.\s*/g,'-').replace(/-$/,'')+'.pdf';
  doc.save(fn);
}

// ── Dodací listy ──
var _dlItems=[], _dlOrder=null, _dlEditId=null, _dlSaved=false;

var _dlCatActive='', _dlCatQty={};

function _fillDLKatalog(){
  _dlCatQty={};
  var cats=[];
  P.forEach(function(p,i){ if(!deleted[i]&&!archived[i]&&cats.indexOf(p.cat)<0) cats.push(p.cat); });
  if(!_dlCatActive||cats.indexOf(_dlCatActive)<0) _dlCatActive=cats[0]||'';
  // tabs
  var tabsEl=document.getElementById('dl-cat-tabs');
  if(!tabsEl) return;
  tabsEl.innerHTML='';
  cats.forEach(function(cat){
    var btn=document.createElement('button');
    btn.className='dl-cat-tab'+(cat===_dlCatActive?' active':'');
    btn.textContent=cat;
    btn.onclick=function(){ _dlCatActive=cat; _renderDLCatGrid(); document.querySelectorAll('.dl-cat-tab').forEach(function(b){b.classList.toggle('active',b.textContent===cat);}); };
    tabsEl.appendChild(btn);
  });
  _renderDLCatGrid();
}

function _renderDLCatGrid(){
  var grid=document.getElementById('dl-prod-grid');
  if(!grid) return;
  var prods=P.map(function(p,i){return Object.assign({},p,{idx:i});})
    .filter(function(p){return p.cat===_dlCatActive&&!deleted[p.idx]&&!archived[p.idx];});
  prods.sort(function(a,b){
    var aOk=avail[a.idx]?0:1,bOk=avail[b.idx]?0:1;
    if(aOk!==bOk) return aOk-bOk;
    return a.name.localeCompare(b.name,'cs');
  });
  grid.innerHTML='';
  prods.forEach(function(p){
    var ok=avail[p.idx];
    var q=_dlCatQty[p.idx]||0;
    var priceHtml=p.vahy
      ? p.voc_kg+' Kč<span> / kg</span><span class="vahy-badge" style="font-size:9px;margin-left:5px">vážený</span>'
      : p.voc+' Kč<span> / ks</span>';
    var card=document.createElement('div');
    card.className='dl-prod-card'+(ok?'':' unavail');
    card.id='dlcc'+p.idx;
    card.innerHTML='<div class="dl-prod-card-name">'+p.name+'</div>'
      +(p.baleni?'<div style="font-size:10px;color:#837261">'+p.baleni+'</div>':'' )
      +'<div class="dl-prod-card-price">'+priceHtml+'</div>'
      +'<div class="dl-prod-qty-row">'
        +'<button onclick="dlCatQty('+p.idx+',-1)">−</button>'
        +'<input type="number" min="0" value="'+q+'" id="dlcq'+p.idx+'" oninput="_dlCatQty['+p.idx+']=parseInt(this.value)||0;dlCatHighlight('+p.idx+')">'
        +'<button onclick="dlCatQty('+p.idx+',1)">+</button>'
      +'</div>';
    grid.appendChild(card);
  });
}

function dlCatQty(idx,d){
  _dlCatQty[idx]=Math.max(0,(_dlCatQty[idx]||0)+d);
  var inp=document.getElementById('dlcq'+idx); if(inp) inp.value=_dlCatQty[idx];
  dlCatHighlight(idx);
}
function dlCatHighlight(idx){
  var card=document.getElementById('dlcc'+idx);
  if(card) card.style.borderColor=(_dlCatQty[idx]>0)?'#4a7a30':'';
}

function dlPridatVybrane(){
  var added=0;
  Object.keys(_dlCatQty).forEach(function(i){
    var q=_dlCatQty[i]; if(!q) return;
    var p=P[parseInt(i)]; if(!p) return;
    var existing=_dlItems.find(function(it){return it.name===p.name;});
    if(existing){ existing.qty=(existing.qty||0)+q; }
    else { _dlItems.push({name:p.name,baleni:p.baleni||'',qty:q,voc:p.voc,vahy:p.vahy||false,voc_kg:p.voc_kg||0,vahy_kg:0,total:p.voc*q}); }
    added++;
  });
  if(!added){ alert('Nejsou vybrány žádné produkty.'); return; }
  _dlCatQty={};
  _renderDLCatGrid();
  renderDLItems();
}

function _openDLOverlay(){
  _dlCatQty={};
  _fillDLKatalog();
  document.getElementById('dl-note').value='';
  renderDLItems();
  document.getElementById('dl-ov').style.display='block';
}

function openDodaciList(idx){
  _dlOrder=_orders[idx];
  _dlItems=(_dlOrder.items||[]).map(function(it){
    var match=P.find(function(p){return p.name===it.name;});
    var vahy=match?match.vahy:false;
    var voc_kg=match?match.voc_kg:0;
    return Object.assign({},it,{vahy:vahy,voc_kg:voc_kg,vahy_kg:0});
  });
  document.getElementById('dl-f-name').value=_dlOrder.customer_name||'';
  document.getElementById('dl-f-company').value=_dlOrder.company||'';
  document.getElementById('dl-f-ico').value=_dlOrder.ico||'';
  document.getElementById('dl-f-email').value=_dlOrder.email||'';
  document.getElementById('dl-f-phone').value=_dlOrder.phone||'';
  _openDLOverlay();
}

var _contacts=[];
function loadContacts(){ try{ _contacts=JSON.parse(localStorage.getItem('df_contacts')||'[]'); }catch(e){ _contacts=[]; } }
function saveContacts(){ try{ localStorage.setItem('df_contacts',JSON.stringify(_contacts)); }catch(e){} }
function dlAdresarSearch(val){
  var drop=document.getElementById('dl-adresar-drop'); if(!drop) return;
  if(!val||!val.trim()){ drop.style.display='none'; drop.innerHTML=''; return; }
  var q=val.toLowerCase();
  var matches=_contacts.filter(function(c){ return c.name.toLowerCase().indexOf(q)>=0||(c.company||'').toLowerCase().indexOf(q)>=0; });
  if(!matches.length){ drop.style.display='none'; drop.innerHTML=''; return; }
  drop.style.display='block';
  drop.innerHTML=matches.map(function(c){
    var origIdx=_contacts.indexOf(c);
    return '<div class="dl-adresar-item" onmousedown="dlVyplnitKontakt('+origIdx+')">'
      +'<strong>'+c.name+'</strong>'+(c.company?' <span style="opacity:.7">· '+c.company+'</span>':'')+(c.ico?' <span style="opacity:.5;font-size:11px">IČO: '+c.ico+'</span>':'')
      +'</div>';
  }).join('');
}
function dlAdresarHide(){ var drop=document.getElementById('dl-adresar-drop'); if(drop){drop.style.display='none';drop.innerHTML='';} }
function dlVyplnitKontakt(idx){
  var c=_contacts[idx]; if(!c) return;
  document.getElementById('dl-f-name').value=c.name||'';
  document.getElementById('dl-f-company').value=c.company||'';
  document.getElementById('dl-f-ico').value=c.ico||'';
  document.getElementById('dl-f-email').value=c.email||'';
  document.getElementById('dl-f-phone').value=c.phone||'';
  document.getElementById('dl-adresar-q').value='';
  dlAdresarHide();
}
function ulozitKontaktDL(){
  var name=document.getElementById('dl-f-name').value.trim();
  if(!name){ alert('Zadejte jméno zákazníka.'); return; }
  var c={ name:name, company:document.getElementById('dl-f-company').value.trim(), ico:document.getElementById('dl-f-ico').value.trim(), email:document.getElementById('dl-f-email').value.trim(), phone:document.getElementById('dl-f-phone').value.trim() };
  var idx=_contacts.findIndex(function(x){ return x.name===name; });
  if(idx>=0){ _contacts[idx]=c; } else { _contacts.push(c); }
  saveContacts();
  var toast=document.createElement('div');
  toast.textContent='✓ Kontakt uložen do adresáře';
  toast.style.cssText='position:fixed;bottom:32px;left:50%;transform:translateX(-50%);background:#4a7a30;color:#fff;padding:12px 28px;border-radius:12px;font-size:15px;font-weight:600;z-index:9999;box-shadow:0 4px 18px rgba(0,0,0,.3);pointer-events:none;transition:opacity .4s';
  document.body.appendChild(toast);
  setTimeout(function(){toast.style.opacity='0';setTimeout(function(){toast.remove();},400);},2000);
}

function openNovyDodaciList(){
  _dlOrder=null; _dlEditId=null;
  _dlItems=[];
  document.getElementById('dl-f-name').value='';
  document.getElementById('dl-f-company').value='';
  document.getElementById('dl-f-ico').value='';
  document.getElementById('dl-f-email').value='';
  document.getElementById('dl-f-phone').value='';
  document.getElementById('dl-f-delivery-date').value='';
  document.getElementById('dl-adresar-q').value='';
  _openDLOverlay();
}

function upravitDL(id, idx){
  var dl=_dodaciListy[idx];
  if(!dl) return;
  _dlEditId=id;
  _dlOrder=null;
  _dlItems=(dl.items||[]).map(function(it){
    var match=P.find(function(p){return p.name===it.name;});
    return Object.assign({},it,{vahy:match?match.vahy:false,voc_kg:match?match.voc_kg:0,vahy_kg:it.vahy_kg||0});
  });
  document.getElementById('dl-f-name').value=dl.customer_name||'';
  document.getElementById('dl-f-company').value=dl.company||'';
  document.getElementById('dl-f-ico').value=dl.ico||'';
  document.getElementById('dl-f-email').value=dl.customer_email||'';
  document.getElementById('dl-f-phone').value=dl.phone||'';
  document.getElementById('dl-f-delivery-date').value=dl.delivery_date||'';
  document.getElementById('dl-adresar-q').value='';
  document.getElementById('dl-note').value=dl.note||'';
  var btn=document.getElementById('dl-save-btn');
  if(btn){btn.textContent='💾 Uložit změny';}
  _dlCatQty={};
  _fillDLKatalog();
  renderDLItems();
  document.getElementById('dl-ov').style.display='block';
}

function closeDodaciList(){
  if(_dlItems.length>0 && !_dlSaved){
    if(confirm('Chcete dodací list uložit před zavřením?')){
      ulozitDL();
      setTimeout(function(){
        document.getElementById('dl-ov').style.display='none'; _dlItems=[]; _dlOrder=null; _dlEditId=null; _dlSaved=false;
      },800);
      return;
    }
  }
  document.getElementById('dl-ov').style.display='none'; _dlItems=[]; _dlOrder=null; _dlEditId=null; _dlSaved=false;
  ['dl-f-name','dl-f-company','dl-f-ico','dl-f-email','dl-f-phone','dl-f-delivery-date','dl-adresar-q'].forEach(function(id){var el=document.getElementById(id);if(el)el.value='';});
  dlAdresarHide();
  var btn=document.getElementById('dl-save-btn');
  if(btn){btn.textContent='💾 Uložit';btn.style.background='#4a7a30';}
}

function _he(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'); }

function renderDLItems(){
  var html='<table class="dl-items-tbl"><thead><tr><th>Produkt</th><th>Objem</th><th style="text-align:center">Ks</th><th style="text-align:center">Váha (kg)</th><th style="text-align:right">Cena/jedn.</th><th style="text-align:right">Celkem</th><th></th></tr></thead><tbody>';
  _dlItems.forEach(function(it,i){
    var tot=it.vahy ? (it.vahy_kg||0)*(it.voc_kg||0) : (it.qty||0)*(it.voc||0);
    html+='<tr>'
      +'<td><input class="dl-inp" value="'+_he(it.name)+'" oninput="_dlItems['+i+'].name=this.value">'
        +(it.vahy?'<span class="vahy-badge" style="margin-left:6px;font-size:9px">vážený</span>':'')+'</td>'
      +'<td><input class="dl-inp" value="'+_he(it.baleni||'')+'" oninput="_dlItems['+i+'].baleni=this.value" style="width:72px"></td>'
      +'<td style="text-align:center">'
        +'<div style="display:flex;align-items:center;justify-content:center;gap:4px">'
          +'<button onclick="_dlItems['+i+'].qty=Math.max(0,(_dlItems['+i+'].qty||0)-1);renderDLItems()" style="width:32px;height:32px;border-radius:8px;border:none;background:#503f37;color:#DACBBC;font-size:18px;font-weight:800;cursor:pointer;line-height:1;font-family:Inter,sans-serif">−</button>'
          +'<input class="dl-qty" type="number" min="0" value="'+(it.qty||0)+'" oninput="_dlItems['+i+'].qty=parseInt(this.value)||0;recalcDL()" style="width:46px">'
          +'<button onclick="_dlItems['+i+'].qty=(_dlItems['+i+'].qty||0)+1;renderDLItems()" style="width:32px;height:32px;border-radius:8px;border:none;background:#503f37;color:#DACBBC;font-size:18px;font-weight:800;cursor:pointer;line-height:1;font-family:Inter,sans-serif">+</button>'
        +'</div>'
        +(it.vahy&&(it.vahy_kg||0)>0?'<div style="font-size:10px;color:#4a7a30;font-weight:700;margin-top:2px">'+(it.vahy_kg||0).toFixed(3)+' kg</div>':'')
      +'</td>'
      +'<td style="text-align:center">'+(it.vahy
        ? '<input class="dl-qty" type="number" min="0" step="0.01" value="'+(it.vahy_kg||0)+'" oninput="_dlItems['+i+'].vahy_kg=parseFloat(this.value)||0;recalcDL()" style="width:70px">'
        : '<span style="color:#ccc;font-size:12px">—</span>')+'</td>'
      +'<td style="text-align:right">'+(it.vahy
        ? '<input class="dl-price" type="number" min="0" value="'+(it.voc_kg||0)+'" oninput="_dlItems['+i+'].voc_kg=parseFloat(this.value)||0;recalcDL()"> Kč/kg'
        : '<input class="dl-price" type="number" min="0" value="'+(it.voc||0)+'" oninput="_dlItems['+i+'].voc=parseFloat(this.value)||0;recalcDL()"> Kč/ks')+'</td>'
      +'<td style="text-align:right;font-weight:800;color:#503f37;white-space:nowrap" id="dlr'+i+'">'+tot.toFixed(2)+' Kč</td>'
      +'<td><button class="dl-del" onclick="removeDLItem('+i+')">✕</button></td>'
      +'</tr>';
  });
  html+='</tbody></table>';
  document.getElementById('dl-items-wrap').innerHTML=html;
  recalcDL();
}

function recalcDL(){
  var total=0;
  _dlItems.forEach(function(it,i){
    var val=it.vahy ? (it.vahy_kg||0)*(it.voc_kg||0) : (it.qty||0)*(it.voc||0); total+=val;
    var el=document.getElementById('dlr'+i); if(el) el.textContent=val.toFixed(2)+' Kč';
  });
  document.getElementById('dl-total-val').textContent=fmt(total);
}

function removeDLItem(i){ _dlItems.splice(i,1); renderDLItems(); }

function addDLItem(){
  var n=document.getElementById('dl-new-name').value.trim();
  var v=parseFloat(document.getElementById('dl-new-voc').value)||0;
  if(!n){ alert('Zadejte název položky.'); return; }
  _dlItems.push({name:n,baleni:'',qty:1,voc:v,total:v,vahy:false,voc_kg:0,vahy_kg:0});
  document.getElementById('dl-new-name').value='';
  document.getElementById('dl-new-voc').value='';
  renderDLItems();
}

function _getDLMeta(){
  var tb=_dlItems.reduce(function(s,it){return s+(it.vahy?(it.vahy_kg||0)*(it.voc_kg||0):(it.qty||0)*(it.voc||0));},0);
  var datum=new Date().toLocaleDateString('cs-CZ');
  var dlNum='DL-'+new Date().toISOString().slice(0,10).replace(/-/g,'');
  var note=document.getElementById('dl-note').value.trim();
  var cust={
    name: document.getElementById('dl-f-name').value.trim() || ((_dlOrder&&_dlOrder.customer_name)||'Zákazník'),
    company: document.getElementById('dl-f-company').value.trim(),
    ico: document.getElementById('dl-f-ico').value.trim(),
    email: document.getElementById('dl-f-email').value.trim(),
    phone: document.getElementById('dl-f-phone').value.trim()
  };
  var deliveryDate=document.getElementById('dl-f-delivery-date').value||null;
  return {tb:tb,datum:datum,dlNum:dlNum,note:note,cust:cust,deliveryDate:deliveryDate};
}

function _buildDLHtml(m, items, orderAddr){
  var rows='';
  items.forEach(function(it){
    var tot=it.vahy?(it.vahy_kg||0)*(it.voc_kg||0):(it.qty||0)*(it.voc||0);
    rows+='<tr>'
      +'<td>'+it.name+(it.vahy?' <span style="font-size:10px;color:#4a7a30">⚖ vážený</span>':'')+'</td>'
      +'<td>'+(it.baleni||'—')+'</td>'
      +'<td style="text-align:center">'+(it.qty||0)+' ks</td>'
      +'<td style="text-align:center">'+(it.vahy?(it.vahy_kg||0).toFixed(3)+' kg':'—')+'</td>'
      +'<td style="text-align:right">'+(it.vahy?(it.voc_kg||0).toFixed(2)+' Kč/kg':(it.voc||0).toFixed(2)+' Kč/ks')+'</td>'
      +'<td style="text-align:right;font-weight:800">'+tot.toFixed(2)+' Kč</td>'
      +'</tr>';
  });
  var info='';
  if(m.cust.company) info+='<div>'+m.cust.company+'</div>';
  if(m.cust.ico) info+='<div>IČO: '+m.cust.ico+'</div>';
  if(m.cust.email) info+='<div>'+m.cust.email+'</div>';
  if(m.cust.phone) info+='<div>'+m.cust.phone+'</div>';
  if(orderAddr) info+='<div>'+orderAddr+'</div>';
  var pdfName='DL_'+m.cust.name.replace(/\s+/g,'_')+'_'+new Date().toISOString().slice(0,10);
  return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>'+pdfName+'</title><style>'
    +'*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif;}'
    +'body{background:#fff;color:#1e1e1e;padding:20mm 14mm;font-size:9pt;}'
    +'.header{background:#503f37;color:#DACBBC;padding:10px 14px;margin:-20mm -14mm 14mm;display:flex;justify-content:space-between;align-items:center;}'
    +'.header h1{font-size:13pt;font-weight:800;letter-spacing:.03em;}.header small{font-size:7.5pt;opacity:.85;}'
    +'.section-label{font-size:7.5pt;font-weight:800;text-transform:uppercase;letter-spacing:.1em;color:#837261;border-bottom:1px solid #d6cbbf;padding-bottom:3px;margin-bottom:8px;}'
    +'.recipient{margin-bottom:14px;}.recipient .name{font-size:11pt;font-weight:800;margin-bottom:3px;}.recipient div{font-size:8.5pt;color:#503f37;line-height:1.6;}'
    +'table{width:100%;border-collapse:collapse;margin-bottom:10px;}th{background:#503f37;color:#DACBBC;font-size:7.5pt;font-weight:800;padding:5px 7px;text-align:left;}td{padding:5px 7px;font-size:8.5pt;border-bottom:1px solid #e8e0d6;}tr:nth-child(even) td{background:#f5f0ea;}'
    +'.totals{background:#DAC9B8;padding:10px 14px;border-radius:6px;display:flex;flex-direction:column;align-items:flex-end;gap:3px;margin-bottom:14px;}.totals .row{display:flex;gap:40px;font-size:8.5pt;color:#503f37;}.totals .big{font-size:11pt;font-weight:800;color:#1e1e1e;}'
    +'.note{font-size:8pt;color:#837261;font-style:italic;margin-bottom:14px;}'
    +'.sigs{display:flex;justify-content:space-between;margin-top:24px;}.sig{border-top:1px solid #b0a090;padding-top:4px;width:44%;font-size:7.5pt;color:#837261;}'
    +'.footer{position:fixed;bottom:8mm;left:14mm;right:14mm;background:#503f37;color:#DACBBC;text-align:center;font-size:7pt;padding:5px;}@media print{.footer{position:fixed;}}'
    +'</style></head><body>'
    +'<div class="header"><h1>DIVOKÉ FARMY — DODACÍ LIST</h1>'
    +'<div style="text-align:right"><div style="font-size:10pt;font-weight:800">'+m.dlNum+'</div><small>'+m.datum+'</small>'+(m.deliveryDate?'<div style="font-size:7.5pt;color:#DACBBC;opacity:.85;margin-top:2px">Datum doručení: '+new Date(m.deliveryDate+'T12:00:00').toLocaleDateString("cs-CZ")+'</div>':'')+'</div></div>'
    +'<div class="recipient"><div class="section-label">Příjemce</div>'
    +'<div class="name">'+m.cust.name+'</div>'+info+'</div>'
    +'<table><thead><tr><th>Produkt</th><th>Objem</th><th style="text-align:center">Ks</th><th style="text-align:center">Váha (kg)</th><th style="text-align:right">Cena/jedn.</th><th style="text-align:right">Celkem</th></tr></thead><tbody>'+rows+'</tbody></table>'
    +'<div class="totals"><div class="row"><span>Celkem bez DPH:</span><span>'+m.tb.toFixed(2)+' Kč</span></div>'
    +'<div class="row"><span>DPH 12 %:</span><span>'+(m.tb*VAT).toFixed(2)+' Kč</span></div>'
    +'<div class="row big"><span>CELKEM S DPH:</span><span>'+(m.tb*(1+VAT)).toFixed(2)+' Kč</span></div></div>'
    +(m.note?'<div class="note">Poznámka: '+m.note+'</div>':'')
    +'<div class="sigs"><div class="sig">Podpis odesílatele</div><div class="sig">Podpis příjemce</div></div>'
    +'<div class="footer">DF obchodní s.r.o. &nbsp;|&nbsp; IČO: 29279313 &nbsp;|&nbsp; Šebrov 195, 679 22 Lipůvka &nbsp;|&nbsp; divokefarmy.cz</div>'
    +'</body></html>';
}

function stahnoutDL(){
  if(!_dlItems.length){alert('Žádné položky.');return;}
  var m=_getDLMeta();
  var html=_buildDLHtml(m,_dlItems,_dlOrder&&_dlOrder.address?_dlOrder.address:null);
  var blob=new Blob([html],{type:'text/html'});
  var blobUrl=URL.createObjectURL(blob);
  var win=window.open(blobUrl,'_blank','width=850,height=1100');
  win.focus();
  setTimeout(function(){ win.print(); URL.revokeObjectURL(blobUrl); },500);
}

function tiskniUlozeneDLPDF(idx){
  var dl=_dodaciListy[idx]; if(!dl) return;
  var items=dl.items||[];
  var datum=new Date(dl.created_at).toLocaleDateString('cs-CZ');
  var dlNum='DL-'+new Date(dl.created_at).toISOString().slice(0,10).replace(/-/g,'');
  var cust={name:dl.customer_name||'',company:dl.company||'',ico:dl.ico||'',email:dl.customer_email||'',phone:dl.phone||''};
  var tb=dl.total_without_vat||0;
  var rows='';
  items.forEach(function(it){
    var tot=it.vahy?(it.vahy_kg||0)*(it.voc_kg||0):(it.qty||0)*(it.voc||0);
    rows+='<tr>'
      +'<td>'+it.name+(it.vahy?' <span style="font-size:10px;color:#4a7a30">⚖ vážený</span>':'')+'</td>'
      +'<td>'+(it.baleni||'—')+'</td>'
      +'<td style="text-align:center">'+(it.qty||0)+' ks</td>'
      +'<td style="text-align:center">'+(it.vahy?(it.vahy_kg||0).toFixed(3)+' kg':'—')+'</td>'
      +'<td style="text-align:right">'+(it.vahy?(it.voc_kg||0).toFixed(2)+' Kč/kg':(it.voc||0).toFixed(2)+' Kč/ks')+'</td>'
      +'<td style="text-align:right;font-weight:800">'+tot.toFixed(2)+' Kč</td>'
      +'</tr>';
  });
  var info='';
  if(cust.company) info+='<div>'+cust.company+'</div>';
  if(cust.ico) info+='<div>IČO: '+cust.ico+'</div>';
  if(cust.email) info+='<div>'+cust.email+'</div>';
  if(cust.phone) info+='<div>'+cust.phone+'</div>';
  var pdfName='DL_'+cust.name.replace(/\s+/g,'_')+'_'+new Date(dl.created_at).toISOString().slice(0,10);
  var VAT_=0.12;
  var htmlStr='<!DOCTYPE html><html><head><meta charset="utf-8"><title>'+pdfName+'</title><style>'
    +'*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif;}'
    +'body{background:#fff;color:#1e1e1e;padding:20mm 14mm;font-size:9pt;}'
    +'.header{background:#503f37;color:#DACBBC;padding:10px 14px;margin:-20mm -14mm 14mm;display:flex;justify-content:space-between;align-items:center;}'
    +'.header h1{font-size:13pt;font-weight:800;letter-spacing:.03em;}'
    +'.header small{font-size:7.5pt;opacity:.85;}'
    +'.section-label{font-size:7.5pt;font-weight:800;text-transform:uppercase;letter-spacing:.1em;color:#837261;border-bottom:1px solid #d6cbbf;padding-bottom:3px;margin-bottom:8px;}'
    +'.recipient{margin-bottom:14px;}.recipient .name{font-size:11pt;font-weight:800;margin-bottom:3px;}.recipient div{font-size:8.5pt;color:#503f37;line-height:1.6;}'
    +'table{width:100%;border-collapse:collapse;margin-bottom:10px;}th{background:#503f37;color:#DACBBC;font-size:7.5pt;font-weight:800;padding:5px 7px;text-align:left;}td{padding:5px 7px;font-size:8.5pt;border-bottom:1px solid #e8e0d6;}tr:nth-child(even) td{background:#f5f0ea;}'
    +'.totals{background:#DAC9B8;padding:10px 14px;border-radius:6px;display:flex;flex-direction:column;align-items:flex-end;gap:3px;margin-bottom:14px;}'
    +'.totals .row{display:flex;gap:40px;font-size:8.5pt;color:#503f37;}.totals .big{font-size:11pt;font-weight:800;color:#1e1e1e;}'
    +'.note{font-size:8pt;color:#837261;font-style:italic;margin-bottom:14px;}'
    +'.sigs{display:flex;justify-content:space-between;margin-top:24px;}.sig{border-top:1px solid #b0a090;padding-top:4px;width:44%;font-size:7.5pt;color:#837261;}'
    +'.footer{position:fixed;bottom:8mm;left:14mm;right:14mm;background:#503f37;color:#DACBBC;text-align:center;font-size:7pt;padding:5px;}@media print{.footer{position:fixed;}}'
    +'</style></head><body>'
    +'<div class="header"><h1>DIVOKÉ FARMY — DODACÍ LIST</h1>'
    +'<div style="text-align:right"><div style="font-size:10pt;font-weight:800">'+dlNum+'</div><small>'+datum+'</small>'+(dl.delivery_date?'<div style="font-size:7.5pt;color:#DACBBC;opacity:.85;margin-top:2px">Datum doručení: '+new Date(dl.delivery_date+'T12:00:00').toLocaleDateString('cs-CZ')+'</div>':'')+'</div></div>'
    +'<div class="recipient"><div class="section-label">Příjemce</div>'
    +'<div class="name">'+cust.name+'</div>'+info+'</div>'
    +'<table><tr><th>Produkt</th><th>Balení</th><th style="text-align:center">Ks</th><th style="text-align:center">Váha</th><th style="text-align:right">Cena</th><th style="text-align:right">Celkem</th></tr>'+rows+'</table>'
    +'<div class="totals"><div class="row"><span>Celkem bez DPH</span><span>'+tb.toFixed(2)+' Kč</span></div><div class="row"><span>DPH 12%</span><span>'+(tb*VAT_).toFixed(2)+' Kč</span></div><div class="row big"><span>Celkem s DPH</span><span>'+(tb*(1+VAT_)).toFixed(2)+' Kč</span></div></div>'
    +(dl.note?'<div class="note">Poznámka: '+dl.note+'</div>':'')
    +'<div class="sigs"><div class="sig">Podpis odesílatele</div><div class="sig">Podpis příjemce</div></div>'
    +'<div class="footer">DF obchodní s.r.o. &nbsp;|&nbsp; IČO: 29279313 &nbsp;|&nbsp; Šebrov 195, 679 22 Lipůvka &nbsp;|&nbsp; divokefarmy.cz</div>'
    +'</body></html>';
  var blob=new Blob([htmlStr],{type:'text/html'});
  var blobUrl=URL.createObjectURL(blob);
  var win=window.open(blobUrl,'_blank','width=850,height=1100');
  win.focus();
  setTimeout(function(){ win.print(); URL.revokeObjectURL(blobUrl); },500);
}

function stahnoutDLSoubor(){
  if(!_dlItems.length){alert('Žádné položky.');return;}
  var m=_getDLMeta();
  var html=_buildDLHtml(m,_dlItems);
  var pdfName='DL_'+m.cust.name.replace(/\s+/g,'_')+'_'+new Date().toISOString().slice(0,10)+'.html';
  var blob=new Blob([html],{type:'text/html'});
  var a=document.createElement('a');
  a.href=URL.createObjectURL(blob);
  a.download=pdfName;
  document.body.appendChild(a);
  a.click();
  setTimeout(function(){ URL.revokeObjectURL(a.href); a.remove(); },1000);
}

function odeslatDL(){
  if(!_dlItems.length){alert('Žádné položky.');return;}
  var m=_getDLMeta();
  if(!m.cust.name){alert('Zadejte prosím jméno zákazníka.');return;}
  stahnoutDL();
  _db.from('delivery_notes').insert([{
    order_id:_dlOrder?_dlOrder.id:null,
    customer_name:m.cust.name,
    customer_email:m.cust.email||null,
    company:m.cust.company||null,
    phone:m.cust.phone||null,
    items:_dlItems.map(function(it){return{name:it.name,baleni:it.baleni||'',qty:it.qty||0,voc:it.voc||0,total:(it.qty||0)*(it.voc||0)};}),
    total_without_vat:m.tb, note:m.note||null
  }]).then(function(res){if(res.error)console.warn('DL save:',res.error.message);});
  if(!m.cust.email){return;}
  var subj='Dodací list '+m.dlNum+' – '+m.cust.name;
  var body='Dobrý den,\n\npřikládáme dodací list '+m.dlNum+' ze dne '+m.datum+'.\n\nCelkem bez DPH: '+m.tb.toFixed(2)+' Kč\nCelkem s DPH: '+(m.tb*(1+VAT)).toFixed(2)+' Kč\n\nS pozdravem\nDivoké Farmy';
  setTimeout(function(){
    window.location.href='mailto:'+encodeURIComponent(m.cust.email)+'?subject='+encodeURIComponent(subj)+'&body='+encodeURIComponent(body);
  },800);
}

function ulozitDL(){
  if(!_dlItems.length){alert('Žádné položky.');return;}
  var m=_getDLMeta();
  if(!m.cust.name){alert('Zadejte prosím jméno zákazníka.');return;}
  var btn=document.getElementById('dl-save-btn');
  if(btn){btn.disabled=true;btn.textContent='Ukládám…';}
  var data={
    customer_name:m.cust.name,
    customer_email:m.cust.email||null,
    company:m.cust.company||null,
    ico:m.cust.ico||null,
    phone:m.cust.phone||null,
    delivery_date:m.deliveryDate||null,
    items:_dlItems.map(function(it){return{name:it.name,baleni:it.baleni||'',qty:it.qty||0,voc:it.voc||0,vahy:it.vahy||false,voc_kg:it.voc_kg||0,vahy_kg:it.vahy_kg||0,total:(it.vahy?(it.vahy_kg||0)*(it.voc_kg||0):(it.qty||0)*(it.voc||0))};}),
    total_without_vat:m.tb, note:m.note||null
  };
  var req;
  if(_dlEditId){
    req=_db.from('delivery_notes').update(data).eq('id',_dlEditId);
  } else {
    data.order_id=_dlOrder?_dlOrder.id:null;
    req=_db.from('delivery_notes').insert([data]);
  }
  req.then(function(res){
    if(btn){btn.disabled=false;}
    if(res.error){alert('Chyba při ukládání: '+res.error.message);return;}
    _dlSaved=true;
    btn.textContent='✓ Uloženo';
    btn.style.background='#2d5a1b';
    setTimeout(function(){if(btn){btn.textContent=_dlEditId?'💾 Uložit změny':'💾 Uložit';btn.style.background='#4a7a30';}},2500);
    var toast=document.createElement('div');
    toast.textContent='✓ Dodací list byl uložen';
    toast.style.cssText='position:fixed;bottom:32px;left:50%;transform:translateX(-50%);background:#2d5a1b;color:#fff;padding:12px 28px;border-radius:12px;font-size:15px;font-weight:600;z-index:9999;box-shadow:0 4px 18px rgba(0,0,0,.3);pointer-events:none;transition:opacity .4s';
    document.body.appendChild(toast);
    setTimeout(function(){toast.style.opacity='0';setTimeout(function(){toast.remove();},400);},2000);
  });
}

var _dodaciListy=[];
function loadDodaciListy(){
  document.getElementById('dl-list').innerHTML='<div class="orders-msg">Načítám dodací listy…</div>';
  _db.from('delivery_notes').select('*').order('created_at',{ascending:false}).then(function(res){
    if(res.error){document.getElementById('dl-list').innerHTML='<div class="orders-msg">Chyba: '+res.error.message+'</div>';return;}
    _dodaciListy=res.data||[]; renderDodaciListy();
  });
}
function renderDodaciListy(){
  var list=document.getElementById('dl-list');
  if(!_dodaciListy.length){list.innerHTML='<div class="orders-msg">Zatím žádné dodací listy.</div>';return;}
  var archivedIds;
  try{ archivedIds=JSON.parse(localStorage.getItem('df_dl_arch')||'[]'); }catch(e){ archivedIds=[]; }
  var html='<div class="orders-list">';
  _dodaciListy.forEach(function(dl,idx){
    var d=new Date(dl.created_at).toLocaleDateString('cs-CZ');
    var items=dl.items||[];
    var isArch=archivedIds.indexOf(dl.id)>=0;
    var dlStatus=dl.status||'odeslano';
    var isVyrizena=dlStatus==='vyrizeno';
    var irows=items.map(function(it){
      var qty=(it.qty||0)+' ks'+(it.vahy&&it.vahy_kg?'<br><span style="font-size:10px;color:#4a7a30;font-weight:700">'+parseFloat(it.vahy_kg).toFixed(3)+' kg</span>':'');
      return'<tr><td>'+(it.name||'')+(it.baleni?' ('+it.baleni+')':'')+'</td><td style="text-align:center">'+qty+'</td><td style="text-align:right;font-weight:800">'+(it.total||0).toFixed(2)+' Kč</td></tr>';
    }).join('');
    var statusBadge=isArch
      ?'<span class="order-status st-archivovana">Archivováno</span>'
      :(isVyrizena
        ?'<span class="st-dl-vyrizena" id="dlstlbl'+idx+'">✓ Vyřízeno</span>'
        :'<span class="st-dl-odeslano" id="dlstlbl'+idx+'">Odesláno</span>');
    var deliveryDateStr=dl.delivery_date?new Date(dl.delivery_date+'T12:00:00').toLocaleDateString('cs-CZ'):'';
    html+='<div class="order-card'+(isArch?' storno-card':'')+(isVyrizena?' dl-card-vyrizena':'')+'" id="dlc'+idx+'">'
      +'<div class="order-hd" onclick="this.nextElementSibling.classList.toggle(\'show\')">'
      +'<span class="order-date">'+(deliveryDateStr?deliveryDateStr:d)+'</span>'
      +'<span class="order-name">'+(dl.customer_name||'')+(dl.company?'<br><small style="font-size:11px;font-weight:500;opacity:.65">'+dl.company+'</small>':'')+'</span>'
      +'<span class="order-total">'+(dl.total_without_vat||0).toFixed(2)+' Kč</span>'
      +statusBadge
      +'</div>'
      +'<div class="order-body">'
      +'<div class="order-info">'+(dl.ico?'IČO: '+dl.ico+' · ':'')+''+(dl.customer_email?dl.customer_email:'')+(dl.phone?' · '+dl.phone:'')+'</div>'
      +'<table class="order-items-tbl"><tr><th>Produkt</th><th style="text-align:center">Množství</th><th style="text-align:right">Celkem</th></tr>'+irows+'</table>'
      +'<div class="order-actions">'
      +'<button class="order-pdf-btn" onclick="tiskniUlozeneDLPDF('+idx+')">🖨 PDF / Tisk</button>'
      +(isArch?'':(!isVyrizena
        ?'<button class="muted-btn" style="background:rgba(74,122,48,0.12);color:#2d5a1b;border-color:rgba(74,122,48,0.3)" onclick="setDLStatus(\''+dl.id+'\','+idx+',\'vyrizeno\')">✓ Označit vyřízeno</button>'
        :'<button class="muted-btn" onclick="setDLStatus(\''+dl.id+'\','+idx+',\'odeslano\')">↩ Odznačit</button>'))
      +'<button class="muted-btn" onclick="upravitDL(\''+dl.id+'\','+idx+')">✎ Upravit</button>'
      +'<button class="muted-btn" onclick="archivujDL(\''+dl.id+'\','+idx+')">'+(isArch?'↩ Obnovit':'📦 Archivovat')+'</button>'
      +'<button class="danger-btn" style="border-color:rgba(100,0,0,0.3);background:rgba(100,0,0,0.07);color:#800" onclick="smazatDL(\''+dl.id+'\','+idx+')">🗑 Smazat</button>'
      +'</div>'
      +'</div></div>';
  });
  html+='</div>'; list.innerHTML=html;
}
function archivujDL(id,idx){
  try{
    var arch=JSON.parse(localStorage.getItem('df_dl_arch')||'[]');
    var pos=arch.indexOf(id);
    if(pos>=0) arch.splice(pos,1); else arch.push(id);
    localStorage.setItem('df_dl_arch',JSON.stringify(arch));
  }catch(e){}
  renderDodaciListy();
}
function setDLStatus(id,idx,status){
  _db.from('delivery_notes').update({status:status}).eq('id',id).then(function(res){
    if(res.error){ alert('Chyba: '+res.error.message+'\n\nPotřebuješ přidat sloupec:\nALTER TABLE delivery_notes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT \'odeslano\';'); return; }
    if(_dodaciListy[idx]) _dodaciListy[idx].status=status;
    renderDodaciListy();
  });
}
function smazatDL(id,idx){
  if(!confirm('Opravdu trvale smazat tento dodací list? Tato akce je nevratná.')) return;
  _db.from('delivery_notes').delete().eq('id',id).then(function(res){
    if(res.error){ alert('Chyba při mazání: '+res.error.message+'\n\nPravděpodobně chybí SQL politika — spusť v Supabase:\nCREATE POLICY "admin_delete_delivery_notes" ON delivery_notes FOR DELETE TO authenticated USING (true);'); return; }
    _dodaciListy=_dodaciListy.filter(function(dl){ return dl.id!==id; });
    renderDodaciListy();
  });
}

// ── Customer Auth ──
var _user = null;

function _onAuthChange(user){
  _user = user;
  var guest = document.getElementById('auth-bar-guest');
  var loggedIn = document.getElementById('auth-bar-user');
  var lbl = document.getElementById('auth-email-lbl');
  var adminLink = document.getElementById('auth-admin-link');
  if(user){
    if(guest) guest.style.display='none';
    if(loggedIn) loggedIn.style.display='flex';
    if(lbl) lbl.textContent = user.email;
    if(adminLink) adminLink.style.display = _isAdmin() ? 'inline' : 'none';
    _prefillFromLastOrder(user.id);
    if(_adminPendingOpen){
      _adminPendingOpen = false;
      if(_isAdmin()) openAdmin();
      else alert('Tento účet nemá administrátorská oprávnění.');
    }
  } else {
    if(guest) guest.style.display='flex';
    if(loggedIn) loggedIn.style.display='none';
  }
}

function openAuthModal(tab){
  document.getElementById('auth-ov').className='show';
  document.getElementById('auth-err').textContent='';
  document.getElementById('auth-email').value='';
  document.getElementById('auth-pw').value='';
  switchAuthTab(tab||'login');
  setTimeout(function(){ document.getElementById('auth-email').focus(); },80);
}
function closeAuthModal(){ document.getElementById('auth-ov').className=''; }

function switchAuthTab(tab){
  var isLogin=tab==='login';
  document.getElementById('tab-login').classList.toggle('act',isLogin);
  document.getElementById('tab-register').classList.toggle('act',!isLogin);
  document.getElementById('auth-submit-btn').textContent=isLogin?'Přihlásit se':'Registrovat';
  document.getElementById('auth-ov').dataset.tab=tab;
}

function doAuthSubmit(){
  var email=document.getElementById('auth-email').value.trim();
  var pw=document.getElementById('auth-pw').value;
  var err=document.getElementById('auth-err');
  var tab=document.getElementById('auth-ov').dataset.tab||'login';
  if(!email||!pw){ err.textContent='Vyplňte e-mail a heslo.'; return; }
  if(pw.length<6){ err.textContent='Heslo musí mít alespoň 6 znaků.'; return; }
  var btn=document.getElementById('auth-submit-btn');
  btn.disabled=true; btn.textContent='Načítám…';
  var p=tab==='login'
    ? _db.auth.signInWithPassword({email:email,password:pw})
    : _db.auth.signUp({email:email,password:pw});
  p.then(function(res){
    btn.disabled=false; btn.textContent=tab==='login'?'Přihlásit se':'Registrovat';
    if(res.error){ err.textContent=res.error.message; return; }
    closeAuthModal();
    if(tab==='register') alert('Registrace proběhla úspěšně! Jste přihlášeni.');
  });
}

function doLogout(){
  _db.auth.signOut();
}

function openMyOrders(){
  document.getElementById('myord-ov').className='show';
  loadMyOrders();
}
function closeMyOrders(){ document.getElementById('myord-ov').className=''; }

function loadMyOrders(){
  if(!_user) return;
  var list=document.getElementById('myord-list');
  list.innerHTML='<div class="orders-msg">Načítám…</div>';
  _db.from('orders').select('*').eq('user_id',_user.id).order('created_at',{ascending:false}).then(function(res){
    if(res.error){ list.innerHTML='<div class="orders-msg">Chyba: '+res.error.message+'</div>'; return; }
    var orders=res.data||[];
    if(!orders.length){ list.innerHTML='<div class="orders-msg">Zatím žádné objednávky.</div>'; return; }
    var stLabel={nova:'Nová',vyrizuje_se:'Vyřizuje se',vyrizena:'Vyřízena',storno:'Storno',archivovana:'Archivováno'};
    var stCls={nova:'st-nova',vyrizuje_se:'st-vyrizuje',vyrizena:'st-vyrizena',storno:'st-storno',archivovana:'st-archivovana'};
    var html='<div class="orders-list">';
    orders.forEach(function(o){
      var d=new Date(o.created_at).toLocaleDateString('cs-CZ');
      var st=o.status||'nova';
      var items=o.items||[];
      var irows=items.map(function(it){
        return '<tr><td>'+(it.name||'')+(it.baleni?' ('+it.baleni+')':'')+'</td>'
          +'<td style="text-align:center">'+it.qty+' ks</td>'
          +'<td style="text-align:right;font-weight:800">'+it.total.toFixed(2)+' Kč</td></tr>';
      }).join('');
      html+='<div class="order-card">'
        +'<div class="order-hd" onclick="this.nextElementSibling.classList.toggle(\'show\')">'
        +'<span class="order-date">'+d+'</span>'
        +'<span class="order-total">'+o.total_without_vat.toFixed(2)+' Kč</span>'
        +'<span class="order-status '+(stCls[st]||'st-nova')+'">'+(stLabel[st]||'Nová')+'</span>'
        +'</div>'
        +'<div class="order-body">'
        +'<table class="order-items-tbl"><tr><th>Produkt</th><th style="text-align:center">Množství</th><th style="text-align:right">Celkem</th></tr>'+irows+'</table>'
        +'</div></div>';
    });
    html+='</div>';
    list.innerHTML=html;
  });
}

function _prefillFromLastOrder(userId){
  var jmeno=document.getElementById('jmeno');
  if(jmeno&&jmeno.value.trim()) return;
  _db.from('orders').select('customer_name,company,email,phone,address').eq('user_id',userId).order('created_at',{ascending:false}).limit(1).then(function(res){
    if(res.error||!res.data||!res.data.length) return;
    var o=res.data[0];
    var map={jmeno:'customer_name',firma:'company',email:'email',tel:'phone',adr:'address'};
    Object.keys(map).forEach(function(id){
      var el=document.getElementById(id);
      if(el&&!el.value.trim()&&o[map[id]]) el.value=o[map[id]];
    });
  });
}

// Init auth state
_db.auth.getUser().then(function(res){ if(res.data&&res.data.user) _onAuthChange(res.data.user); });
_db.auth.onAuthStateChange(function(event,session){ _onAuthChange(session?session.user:null); });

// Auth modal keyboard
document.getElementById('auth-pw').addEventListener('keydown',function(e){ if(e.key==='Enter') doAuthSubmit(); });

function toggleTheme(){
  var light=document.body.classList.toggle('light');
  localStorage.setItem('df_theme',light?'light':'dark');
  document.getElementById('btn-theme').textContent=light?'🌙':'☀';
}

// DATE
document.getElementById('dnes').textContent=new Date().toLocaleDateString('cs-CZ',{day:'numeric',month:'long',year:'numeric'});

// Init theme
(function(){ if(localStorage.getItem('df_theme')==='light'){ document.body.classList.add('light'); document.getElementById('btn-theme').textContent='🌙'; } })();

// Remember-me autofill
(function(){
  try{
    var saved=localStorage.getItem('df_customer');
    if(saved){
      var c=JSON.parse(saved);
      ['jmeno','firma','email','tel','adr'].forEach(function(id){ var el=document.getElementById(id); if(el&&c[id]) el.value=c[id]; });
      document.getElementById('remember-me').checked=true;
      document.getElementById('forget-link').style.display='inline';
    }
  }catch(e){}
})();

// Load product state: Supabase first, localStorage fallback
document.getElementById('pc').innerHTML='<div style="padding:32px 0;text-align:center;color:#837261;font-size:13px;font-weight:600;letter-spacing:.04em;">Načítám produkty…</div>';
loadContacts();
_db.from('product_state').select('*').eq('id',1).single().then(function(res){
  if(!res.error && res.data){
    _applyState(res.data);
  } else {
    try{ var s=localStorage.getItem('df_av'); if(s) Object.assign(avail,JSON.parse(s)); }catch(e){}
    try{ var po=localStorage.getItem('df_po'); if(po){ prodOverrides=JSON.parse(po); Object.keys(prodOverrides).forEach(function(i){ if(P[i]) Object.assign(P[i],prodOverrides[i]); }); } }catch(e){}
    try{ var ar=localStorage.getItem('df_arch'); if(ar) archived=JSON.parse(ar); }catch(e){}
    try{ var dl=localStorage.getItem('df_del'); if(dl) deleted=JSON.parse(dl); }catch(e){}
    try{ var cp=localStorage.getItem('df_cp'); if(cp){ customProds=JSON.parse(cp); customProds.forEach(function(p){ P.push(Object.assign({_custom:true},p)); }); } }catch(e){}
    try{ var po2=localStorage.getItem('df_po'); if(po2){ var po2p=JSON.parse(po2); Object.keys(po2p).forEach(function(i){ if(po2p[i]&&po2p[i].stock>0) stockQty[i]=po2p[i].stock; }); } }catch(e){}
  }
  buildAll();
});

