// Runtime configuration — copy to `config.js` for local development.
// In production this file is generated by .github/workflows/deploy.yml from
// repository secrets. `config.js` is gitignored.
//
// All values listed here are exposed to the browser. Treat the Supabase key as
// the *anon* key (security comes from RLS), and use only the EmailJS *public*
// key. Never put server-role / private keys in this file.
window.DF_CONFIG = {
  SUPABASE_URL:        '',
  SUPABASE_ANON_KEY:   '',
  EMAILJS_PUBLIC_KEY:  '',
  EMAILJS_SERVICE_ID:  '',
  EMAILJS_TEMPLATE_ID: '',
  ADMIN_PW:            '',
  EMAIL_TO:            'adam@divokefarmy.cz'
};
