// Runtime configuration — copy to `config.js` for local development.
// In production this file is generated by .github/workflows/deploy.yml from
// repository secrets. `config.js` is gitignored.
//
// Every value here is delivered to the browser. Use ONLY public-by-design
// credentials: the Supabase *anon* key (security comes from RLS) and the
// EmailJS *public* key. Never put server-role / private keys in this file.
//
// Admin access is gated by Supabase Auth + RLS, not by anything in this file.
// See docs/admin-setup.md for how to provision an admin user.
window.DF_CONFIG = {
  SUPABASE_URL:        '',
  SUPABASE_ANON_KEY:   '',
  EMAILJS_PUBLIC_KEY:  '',
  EMAILJS_SERVICE_ID:  '',
  EMAILJS_TEMPLATE_ID: '',
  EMAIL_TO:            'adam@divokefarmy.cz'
};
